<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_MJpicB0JEe-wwLkYj99nvQ" name="Conceber_solucao" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_MJpicR0JEe-wwLkYj99nvQ" name="Conceber a Solução">
      <elements xmi:type="process:Lane" xmi:id="_MJpich0JEe-wwLkYj99nvQ" name="Gestor OV" actor="_IfqIQCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:ServiceTask" xmi:id="_QFJ7MB24Ee-gZr0NkXqK5g" name="Carregar OV" outgoing="_R5KPcB24Ee-gZr0NkXqK5g" incoming="_DVNq0CleEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MJpieB0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MJpieR0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MJpieh0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_cW4gEDDTEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_cW4gETDTEe-1LbipnKYqtw" name="emailMessage" content="emailMessage" type="TYPE_VARIABLE" returnType="com.company.model.EmailMessage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dBgKYDDTEe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_cW4gEjDTEe-1LbipnKYqtw" name="newScript()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_cW4gEzDTEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_evjAkDDTEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_evjAkTDTEe-1LbipnKYqtw" name="emailMessage" content="emailMessage" type="TYPE_VARIABLE" returnType="com.company.model.EmailMessage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_fFk68DDTEe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_evjAkjDTEe-1LbipnKYqtw" name="newScript()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_evjAkzDTEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setMessage">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_gk8b8DDTEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_gk8b8TDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hB6r0DDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_gk8b8jDTEe-1LbipnKYqtw" name="newScript()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_gk8b8zDTEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_ko8c4DDTEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_ko8c4TDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_lAW3UDDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_ko8c4jDTEe-1LbipnKYqtw" name="newScript()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_ko8c4zDTEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_m3IywDDTEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_m3IywTDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nJS5wDDTEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_m3IywjDTEe-1LbipnKYqtw" name="newScript()" content="''" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT"/>
            <operator xmi:type="expression:Operator" xmi:id="_m3IywzDTEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setCalendarizacao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MJpiex0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MJpifB0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MJpifR0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MJpifh0JEe-wwLkYj99nvQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MJpifx0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_rmg-cB24Ee-gZr0NkXqK5g" name="Solução cancelada, não é uma venda de solução" incoming="_rmkBwB24Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rmhlgR24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rmhlgB24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rmhlgh24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_QDi8MB25Ee-gZr0NkXqK5g" name="Carregar e respeitar &quot;Catálogo de Serviço  da empresa&quot;" outgoing="_aLA7cB25Ee-gZr0NkXqK5g" incoming="_QDkxYB25Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QDjjQR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QDjjQB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QDjjQh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QDjjQx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QDjjRB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QDjjRR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QDjjRx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QDjjRh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_e5Mh0B25Ee-gZr0NkXqK5g" name="Conceção da solução" outgoing="_tGo38B25Ee-gZr0NkXqK5g" incoming="_aLA7cB25Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aK_tUR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aK_tUB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aK_tUh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_mziW8C_oEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mziW8S_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mziW8i_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mziW8y_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mziW9C_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mziW9S_oEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mziW9i_oEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mziW9y_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mziW-C_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mziW-S_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mziW-i_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mziW-y_oEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_mziW_C_oEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_mziW_S_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mziW_i_oEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_mziW_y_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_mziXAC_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_mziXAS_oEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aK_tUx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aK_tVB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aK_tVR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aK_tVx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aK_tVh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_e5NI6R25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_q5dqgC_oEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_e5NI6B25Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_mzghwC_oEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_mzghwS_oEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzghwi_oEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_mzghwy_oEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_e5NI6x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_R-hlsB26Ee-gZr0NkXqK5g" name="Conceber melhor solução para o cliente e elaborar justificações" outgoing="_btmTEB26Ee-gZr0NkXqK5g" incoming="_IQ1YYB26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IQ0KQh26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IQ0KQR26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IQ0KQx26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Y7IVVC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Y7IVVS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Y7IVVi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Y7IVVy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Y7IVWC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Y7IVWS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Y7IVWi_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Y7IVWy_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Y7IVXC_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Y7I8YC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Y7I8YS_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Y7I8Yi_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Y7I8Yy_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Y7I8ZC_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Y7I8ZS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Y7I8Zi_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Y7I8Zy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Y7I8aC_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IQ0KRB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IQ0KRR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IQ0KRh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IQ0KSB26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IQ0KRx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_R-iMxx26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_aC85AC_rEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_R-iMxh26Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_Y7IVUC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Y7IVUS_rEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Y7IVUi_rEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Y7IVUy_rEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_R-iMyR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Kl6j8B27Ee-gZr0NkXqK5g" name="Associar solução à OV" outgoing="_OxGK8x27Ee-gZr0NkXqK5g" incoming="_5bGgwCJ7Ee-K9NOFx4MuYQ _xJ8NYDDVEe-1LbipnKYqtw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Kl7LAR27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Kl7LAB27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Kl7LAh27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Kl7LAx27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Kl7LBB27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Kl7LBR27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Kl7LBx27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Kl7LBh27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OxE80B27Ee-gZr0NkXqK5g" name="Guadar OV no CRM" outgoing="_uJbXoClfEe-TMIDnSmPP3w" incoming="_OxGK8x27Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OxFj4R27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OxFj4B27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OxFj4h27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OxFj4x27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OxFj5B27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OxFj5R27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OxFj5x27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OxFj5h27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__2TfECJ6Ee-K9NOFx4MuYQ" name="Retorno dos requisitos" outgoing="_QDkxYB25Ee-gZr0NkXqK5g" incoming="_VdntwC5YEe-SvPntKcWM0A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L5hy0R25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L5hy0B25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L5hy0h25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_pAOboC5hEe-SvPntKcWM0A">
            <leftOperand xmi:type="expression:Expression" xmi:id="_pAPCsC5hEe-SvPntKcWM0A" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_mnr6IC5lEe-SvPntKcWM0A" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_pAPCsS5hEe-SvPntKcWM0A" name="Estes sao os requisitos: vai dar uma volta" content="Estes sao os requisitos: vai dar uma volta"/>
            <operator xmi:type="expression:Operator" xmi:id="_pAPCsi5hEe-SvPntKcWM0A" type="JAVA_METHOD" expression="setRequisitos">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L5hy0x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L5hy1B25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L5hy1R25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L5hy1x25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L5hy1h25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_AlWWYCJ7Ee-K9NOFx4MuYQ" name="1 dia" outgoing="_HCWPACJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_cBwvAClcEe-TMIDnSmPP3w" name="1 Days 00:00:00" content="86400000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_CT_CcCJ7Ee-K9NOFx4MuYQ" name="7 dias" outgoing="_XyX2oCJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_WRNFoClcEe-TMIDnSmPP3w" name="7 Days 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="__2UGKSJ6Ee-K9NOFx4MuYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_GXw_kDDiEe-BQ93tMzjnrA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__2UGKCJ6Ee-K9NOFx4MuYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__2UGKyJ6Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_HCQvcCJ7Ee-K9NOFx4MuYQ" name="Notificar cliente acerca dos requisitos" outgoing="_Odd8wCJ7Ee-K9NOFx4MuYQ" incoming="_HCWPACJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HCRWgSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HCRWgCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HCRWgiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_bMhU0C5ZEe-SvPntKcWM0A" documentation="Email para enviar ao cliente a relembrar os requisitos da OV" name="Notificação do pedido de requisitos" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_bMkYIC5ZEe-SvPntKcWM0A" definitionId="email" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_MC5ZEe-SvPntKcWM0A" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_MS5ZEe-SvPntKcWM0A" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_Mi5ZEe-SvPntKcWM0A" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_My5ZEe-SvPntKcWM0A" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_NC5ZEe-SvPntKcWM0A" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_NS5ZEe-SvPntKcWM0A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_Ni5ZEe-SvPntKcWM0A" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_Ny5ZEe-SvPntKcWM0A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_OC5ZEe-SvPntKcWM0A" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_OS5ZEe-SvPntKcWM0A" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_Oi5ZEe-SvPntKcWM0A" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_Oy5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_PC5ZEe-SvPntKcWM0A" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_PS5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_Pi5ZEe-SvPntKcWM0A" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_Py5ZEe-SvPntKcWM0A" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_QC5ZEe-SvPntKcWM0A" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_QS5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMk_Qi5ZEe-SvPntKcWM0A" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_bMk_Qy5ZEe-SvPntKcWM0A" name="to()" content="oportunidadeDeVenda.email_cliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_l-9tQC5lEe-LUL3cchlqMw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmQS5ZEe-SvPntKcWM0A" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmQi5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmQy5ZEe-SvPntKcWM0A" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmRC5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmRS5ZEe-SvPntKcWM0A" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmRi5ZEe-SvPntKcWM0A" name="Relembramos o pedido de requisitos" content="Relembramos o pedido de requisitos" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmRy5ZEe-SvPntKcWM0A" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmSC5ZEe-SvPntKcWM0A" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmSS5ZEe-SvPntKcWM0A" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmSi5ZEe-SvPntKcWM0A" name="&lt;pattern-expression>" content="&lt;p>&lt;strong>Por favor envie os requisitos da OV.&lt;/strong>&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmSy5ZEe-SvPntKcWM0A" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_bMlmTC5ZEe-SvPntKcWM0A"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmTS5ZEe-SvPntKcWM0A" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmTi5ZEe-SvPntKcWM0A" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmTy5ZEe-SvPntKcWM0A" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_bMlmUC5ZEe-SvPntKcWM0A" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bMlmUS5ZEe-SvPntKcWM0A" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_bMlmUi5ZEe-SvPntKcWM0A"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HCRWgyJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HCRWhCJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HCRWhSJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HCRWhyJ7Ee-K9NOFx4MuYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HCRWhiJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OdcHkCJ7Ee-K9NOFx4MuYQ" name="Cliente Notificado" incoming="_Odd8wCJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OdcuoSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OdcuoCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OdcuoiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_XyWBcCJ7Ee-K9NOFx4MuYQ" name="Concessão cancelada, sem resposta do cliente" incoming="_XyX2oCJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XyWogSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XyWogCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XyWogiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_iVrdUCJ7Ee-K9NOFx4MuYQ" name="Retorno do fornecedor" outgoing="_w7x1kDDVEe-1LbipnKYqtw" incoming="_c9HkMDDUEe-1LbipnKYqtw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BVZa0h27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BVZa0R27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BVZa0x27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_R-AV0DDVEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_R-AV0TDVEe-1LbipnKYqtw" name="respostaFornecedor" content="respostaFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.Fornecedor">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TkH_EDDVEe-1LbipnKYqtw" name="respostaFornecedor" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.Fornecedor"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_R-AV0jDVEe-1LbipnKYqtw" name="newScript()" content="respostaFornecedor.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_YW3VUDDVEe-1LbipnKYqtw" name="respostaFornecedor" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.Fornecedor"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_R-AV0zDVEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_YqRZgDDVEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_YqRZgTDVEe-1LbipnKYqtw" name="respostaFornecedor" content="respostaFornecedor" type="TYPE_VARIABLE" returnType="com.company.model.Fornecedor">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_ZEEZkDDVEe-1LbipnKYqtw" name="respostaFornecedor" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.Fornecedor"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_YqRZgjDVEe-1LbipnKYqtw" name="newScript()" content="emailMessage.message" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_dk0A4DDVEe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_YqRZgzDVEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setResposta">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BVZa1B27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BVZa1R27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BVZa1h27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BVZa2B27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BVZa1x27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_3-mtkCJ7Ee-K9NOFx4MuYQ" name="apos 7 dias" outgoing="_5bGgwCJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_mr0IECPkEe-u9q7LyKFNBA" name="7 Days 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iVtSgiJ7Ee-K9NOFx4MuYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_GXw_kTDiEe-BQ93tMzjnrA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iVtSgSJ7Ee-K9NOFx4MuYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iVtShCJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_Cy8EMCleEe-TMIDnSmPP3w" name="Conceber solução" outgoing="_DVNq0CleEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Cy8EMileEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Cy8EMSleEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Cy8EMyleEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_WeqLcClfEe-TMIDnSmPP3w" name="Solução concebida com sucesso" incoming="_unGLEClfEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WeqygSlfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WeqygClfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WeqygilfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2S3j8ClfEe-TMIDnSmPP3w" name="Gerar solução em pdf" outgoing="_unGLEClfEe-TMIDnSmPP3w" incoming="_uJbXoClfEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_by-kwSlfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_by-kwClfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_by-kwilfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_by-kwylfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_by-kxClfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_by-kxSlfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_by-kxylfEe-TMIDnSmPP3w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_by-kxilfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QGn14ClgEe-TMIDnSmPP3w" name="Contactar fornecedores (preços/prazos/condições de entrega)" outgoing="_c9HkMDDUEe-1LbipnKYqtw" incoming="_-pDwYR26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-pDJUR26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-pDJUB26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-pDJUh26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_4E2t4DDREe-1LbipnKYqtw" documentation="Email para enviar ao fornecedor" name="Pedido de informacao" definitionId="email" event="ON_FINISH" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_4E2t4TDREe-1LbipnKYqtw" definitionId="email" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t4jDREe-1LbipnKYqtw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t4zDREe-1LbipnKYqtw" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t5DDREe-1LbipnKYqtw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t5TDREe-1LbipnKYqtw" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t5jDREe-1LbipnKYqtw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t5zDREe-1LbipnKYqtw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t6DDREe-1LbipnKYqtw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t6TDREe-1LbipnKYqtw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t6jDREe-1LbipnKYqtw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t6zDREe-1LbipnKYqtw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t7DDREe-1LbipnKYqtw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t7TDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t7jDREe-1LbipnKYqtw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t7zDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t8DDREe-1LbipnKYqtw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t8TDREe-1LbipnKYqtw" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t8jDREe-1LbipnKYqtw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t8zDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t9DDREe-1LbipnKYqtw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t9TDREe-1LbipnKYqtw" name="to()" content="emailMessage.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FoeD4DDSEe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t9zDREe-1LbipnKYqtw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t-DDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t-TDREe-1LbipnKYqtw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t-jDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t-zDREe-1LbipnKYqtw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t_DDREe-1LbipnKYqtw" name="Pedido de informação" content="Pedido de informação" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t_TDREe-1LbipnKYqtw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_4E2t_jDREe-1LbipnKYqtw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2t_zDREe-1LbipnKYqtw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_4E2uADDREe-1LbipnKYqtw" name="newScript()" content="emailMessage.message" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FoeD4TDSEe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2uATDREe-1LbipnKYqtw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_4E2uAjDREe-1LbipnKYqtw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2uAzDREe-1LbipnKYqtw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_4E2uBDDREe-1LbipnKYqtw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2uBTDREe-1LbipnKYqtw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_4E2uBjDREe-1LbipnKYqtw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_4E2uBzDREe-1LbipnKYqtw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_4E2uCDDREe-1LbipnKYqtw"/>
              </parameters>
            </configuration>
          </connectors>
          <operations xmi:type="expression:Operation" xmi:id="_OfBDQjDREe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_OfBDQzDREe-1LbipnKYqtw" name="emailMessage" content="emailMessage" type="TYPE_VARIABLE" returnType="com.company.model.EmailMessage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OfBDRDDREe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_OfBDRTDREe-1LbipnKYqtw" name="emailMessageInput.message" content="emailMessageInput?.message" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_OfBDRjDREe-1LbipnKYqtw" name="emailMessageInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_OfBDRzDREe-1LbipnKYqtw" type="JAVA_METHOD" expression="setMessage">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_OfBDSDDREe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_OfBDSTDREe-1LbipnKYqtw" name="emailMessage" content="emailMessage" type="TYPE_VARIABLE" returnType="com.company.model.EmailMessage">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OfBDSjDREe-1LbipnKYqtw" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_OfBDSzDREe-1LbipnKYqtw" name="emailMessageInput.email" content="emailMessageInput?.email" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_OfBDTDDREe-1LbipnKYqtw" name="emailMessageInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_OfBDTTDREe-1LbipnKYqtw" type="JAVA_METHOD" expression="setEmail">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-pDJUx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-pDJVB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-pDJVR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-pDJVx26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-pDJVh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QGoc-SlgEe-TMIDnSmPP3w">
            <targetForm xmi:type="expression:Expression" xmi:id="_REGPIDDREe-1LbipnKYqtw" name="emailForm" content="4b9d7d22-8411-4d57-b0a5-5dc829cd012c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QGoc-ClgEe-TMIDnSmPP3w">
            <inputs xmi:type="process:ContractInput" xmi:id="_OfAcMDDREe-1LbipnKYqtw" name="emailMessageInput" type="COMPLEX" dataReference="emailMessage" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_OfAcMTDREe-1LbipnKYqtw" name="message" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_OfAcMjDREe-1LbipnKYqtw" name="email" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_OfBDQDDREe-1LbipnKYqtw" expression="emailMessageInput?.message != null" errorMessage="message is mandatory for EmailMessage" name="mandatory_emailMessageInput_message">
              <inputNames>emailMessageInput</inputNames>
            </constraints>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_OfBDQTDREe-1LbipnKYqtw" expression="emailMessageInput?.email != null" errorMessage="email is mandatory for EmailMessage" name="mandatory_emailMessageInput_email">
              <inputNames>emailMessageInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QGoc-ylgEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AxMDUCloEe-Q4N-lG7hnAQ" name="Verificar tipo de OV" outgoing="_f5VYUC5QEe-LUL3cchlqMw" incoming="_R5KPcB24Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R5DhwR24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R5DhwB24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R5Dhwh24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_R5Dhwx24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_R5DhxB24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R5DhxR24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_R5Dhxx24Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_R5Dhxh24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1b4EACl_Ee-Q4N-lG7hnAQ" name="Tipo de OV &quot;venda de soluções&quot;?" outgoing="_rmkBwB24Ee-gZr0NkXqK5g _UrrTcC5YEe-SvPntKcWM0A" incoming="_f5VYUC5QEe-LUL3cchlqMw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZmFe4R24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZmFe4B24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZmFe4h24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_60Yv4C5YEe-SvPntKcWM0A" name="Recolha de requisitos" outgoing="_VdntwC5YEe-SvPntKcWM0A" incoming="_UrrTcC5YEe-SvPntKcWM0A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UrIg4C5YEe-SvPntKcWM0A" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UrH50C5YEe-SvPntKcWM0A" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UrIg4S5YEe-SvPntKcWM0A" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_LArbYC_lEe-kMoxTdsEtQg" documentation="Email para enviar ao cliente a pedir requisitos da OV" name="Pedido de requisitos1" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_LArbYS_lEe-kMoxTdsEtQg" definitionId="email" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbYi_lEe-kMoxTdsEtQg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_LArbYy_lEe-kMoxTdsEtQg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbZC_lEe-kMoxTdsEtQg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_LArbZS_lEe-kMoxTdsEtQg" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbZi_lEe-kMoxTdsEtQg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_LArbZy_lEe-kMoxTdsEtQg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbaC_lEe-kMoxTdsEtQg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_LArbaS_lEe-kMoxTdsEtQg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbai_lEe-kMoxTdsEtQg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_LArbay_lEe-kMoxTdsEtQg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbbC_lEe-kMoxTdsEtQg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_LArbbS_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbbi_lEe-kMoxTdsEtQg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_LArbby_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbcC_lEe-kMoxTdsEtQg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_LArbcS_lEe-kMoxTdsEtQg" name="no-reply@acme.com" content="no-reply@acme.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbci_lEe-kMoxTdsEtQg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_LArbcy_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbdC_lEe-kMoxTdsEtQg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_LArbdS_lEe-kMoxTdsEtQg" name="to()" content="oportunidadeDeVenda.email_cliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_LArbdi_lEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbdy_lEe-kMoxTdsEtQg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_LArbeC_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbeS_lEe-kMoxTdsEtQg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_LArbei_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbey_lEe-kMoxTdsEtQg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_LArbfC_lEe-kMoxTdsEtQg" name="Pedido de requisitos" content="Pedido de requisitos" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbfS_lEe-kMoxTdsEtQg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_LArbfi_lEe-kMoxTdsEtQg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbfy_lEe-kMoxTdsEtQg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_LArbgC_lEe-kMoxTdsEtQg" name="&lt;pattern-expression>" content="&lt;p>&lt;strong>Por favor envie os requisitos da OV.&lt;/strong>&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbgS_lEe-kMoxTdsEtQg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_LArbgi_lEe-kMoxTdsEtQg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbgy_lEe-kMoxTdsEtQg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_LArbhC_lEe-kMoxTdsEtQg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbhS_lEe-kMoxTdsEtQg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_LArbhi_lEe-kMoxTdsEtQg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_LArbhy_lEe-kMoxTdsEtQg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_LArbiC_lEe-kMoxTdsEtQg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UrIg4i5YEe-SvPntKcWM0A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UrIg4y5YEe-SvPntKcWM0A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UrIg5C5YEe-SvPntKcWM0A" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UrIg5i5YEe-SvPntKcWM0A" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UrIg5S5YEe-SvPntKcWM0A" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_38oCIDDVEe-1LbipnKYqtw" name="Ajustes na solução/justificação/calendarização" outgoing="_xJ8NYDDVEe-1LbipnKYqtw" incoming="_w7x1kDDVEe-1LbipnKYqtw" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_m1KK4TDVEe-1LbipnKYqtw" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_m1KK4DDVEe-1LbipnKYqtw" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_m1KK4jDVEe-1LbipnKYqtw" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_BfPn5DDWEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BfPn5TDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BfPn5jDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BfPn5zDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BfPn6DDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BfPn6TDWEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_BfPn6jDWEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BfPn6zDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BfPn7DDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BfPn7TDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BfPn7jDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BfPn7zDWEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_BfPn8DDWEe-1LbipnKYqtw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BfPn8TDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BfPn8jDWEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BfPn8zDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput.calendarizacao" content="oportunidadeDeVendaInput?.calendarizacao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BfPn9DDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BfPn9TDWEe-1LbipnKYqtw" type="JAVA_METHOD" expression="setCalendarizacao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_m1KK4zDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_m1KK5DDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_m1KK5TDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_m1KK5zDVEe-1LbipnKYqtw" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_m1KK5jDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_38opOTDVEe-1LbipnKYqtw">
            <targetForm xmi:type="expression:Expression" xmi:id="_F4YLUDDWEe-1LbipnKYqtw" name="newForm3" content="1755be37-4f2c-4e29-af4e-860811cc4f04" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_38opODDVEe-1LbipnKYqtw">
            <inputs xmi:type="process:ContractInput" xmi:id="_BfPn4DDWEe-1LbipnKYqtw" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_BfPn4TDWEe-1LbipnKYqtw" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_BfPn4jDWEe-1LbipnKYqtw" name="justificacoes" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_BfPn4zDWEe-1LbipnKYqtw" name="calendarizacao" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_38opOzDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_UZt0MDDeEe-BQ93tMzjnrA" name="Utilizador que concebe a solução" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_UZt0MTDeEe-BQ93tMzjnrA" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_UZt0MjDeEe-BQ93tMzjnrA" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_UZt0MzDeEe-BQ93tMzjnrA" name="true" content="true" returnType="java.lang.Boolean"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VEyRcB0JEe-wwLkYj99nvQ" name="Equipa Técnica" actor="__SWrMCJ_Ee-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_ty458B25Ee-gZr0NkXqK5g" name="Apoio na conceção da solução" outgoing="_Ca_U8C2VEe-1jpJFqdf7Ng" incoming="_tGo38B25Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tGnp0R25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tGnp0B25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tGnp0h25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_BzcBBC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BzcBBS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BzcBBi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BzcBBy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BzcBCC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BzcBCS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_BzcBCi_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BzcBCy_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BzcBDC_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BzcBDS_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BzcBDi_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BzcBDy_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_BzcBEC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_BzcBES_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BzcBEi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_BzcBEy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_BzcBFC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_BzcBFS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tGnp0x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tGnp1B25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tGnp1R25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tGnp1x25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tGnp1h25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ty5hCR25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_6tzbEC_qEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ty5hCB25Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_BzcBAC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_BzcBAS_rEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_BzcBAi_rEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_BzcBAy_rEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ty5hCx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_dFCnIB26Ee-gZr0NkXqK5g" name="Apoio na conceção da melhor solução para o cliente e elaborar justificações" outgoing="_aRYhIC_sEe-kMoxTdsEtQg" incoming="_btmTEB26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_btlE8B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_btkd4R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_btlE8R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_doA7NC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doA7NS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doA7Ni_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doA7Ny_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_doA7OC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doA7OS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_doA7Oi_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doA7Oy_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doA7PC_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doA7PS_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_doA7Pi_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doA7Py_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_doA7QC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_doA7QS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_doA7Qi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_doA7Qy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_doA7RC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_doA7RS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_btlE8h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_btlE8x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_btlE9B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_btlE9h26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_btlE9R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dFDONh26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_eu-jQC_rEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dFDONR26Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_doA7MC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_doA7MS_rEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_doA7Mi_rEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_doA7My_rEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dFDOOB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0eI0gB26Ee-gZr0NkXqK5g" name="Calcular dias necessários e calendarização do projeto" outgoing="_-pDwYR26Ee-gZr0NkXqK5g" incoming="_aRYhIC_sEe-kMoxTdsEtQg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yzrd0h26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yzrd0R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yzrd0x26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_jJua0i_sEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_jJua0y_sEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_jJua1C_sEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_jJua1S_sEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.calendarizacao" content="oportunidadeDeVendaInput?.calendarizacao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_jJua1i_sEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_jJua1y_sEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setCalendarizacao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yzrd1B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yzsE4B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yzsE4R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yzsE4x26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yzsE4h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0eJblB26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_L6L8oC_tEe-kMoxTdsEtQg" name="newForm2" content="a1fc581b-91db-43b0-9844-e71d65b9dd78" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0eJbkx26Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_jJua0C_sEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_jJua0S_sEe-kMoxTdsEtQg" name="calendarizacao" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0eJblh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VTusYB0JEe-wwLkYj99nvQ" name="Serviços de Apoio ao Negócio (área logística)" actor="_NiFgUCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_7W0ZAB25Ee-gZr0NkXqK5g" name="Apoio na coordenação de recursos (logistica)" outgoing="_AscZ4R26Ee-gZr0NkXqK5g" incoming="_Ca_U8C2VEe-1jpJFqdf7Ng" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5vQlUR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5vQlUB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5vQlUh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_RlaE9C_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RlaE9S_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RlaE9i_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RlaE9y_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RlaE-C_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RlaE-S_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_RlaE-i_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RlaE-y_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RlaE_C_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RlaE_S_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RlaE_i_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RlaE_y_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_RlaFAC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_RlaFAS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RlaFAi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_RlaFAy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_RlaFBC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_RlaFBS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5vQlUx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5vQlVB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5vQlVR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5vQlVx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5vQlVh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_7W1nKR25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_D-gxeC_rEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_7W1nKB25Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_RlaE8C_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_RlaE8S_rEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_RlaE8i_rEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_RlaE8y_rEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_7W2OMB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Vkvj4B0JEe-wwLkYj99nvQ" name="Serviços de Apoio ao Negócio (área comercial)" actor="_VVkDsCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_BTrZAB26Ee-gZr0NkXqK5g" name="Apoio na coordenação de recursos (comercial)" outgoing="_IQ1YYB26Ee-gZr0NkXqK5g" incoming="_AscZ4R26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Asby0R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Asby0B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Asby0h26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_UbMmUC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UbMmUS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UbMmUi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UbMmUy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.descricao" content="oportunidadeDeVendaInput?.descricao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UbMmVC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UbMmVS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setDescricao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UbMmVi_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UbMmVy_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UbMmWC_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UbMmWS_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.solucao" content="oportunidadeDeVendaInput?.solucao" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UbMmWi_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UbMmWy_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setSolucao">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_UbMmXC_rEe-kMoxTdsEtQg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_UbMmXS_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" content="oportunidadeDeVenda" type="TYPE_VARIABLE" returnType="com.company.model.OportunidadeDeVenda">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_UbMmXi_rEe-kMoxTdsEtQg" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_UbMmXy_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput.justificacoes" content="oportunidadeDeVendaInput?.justificacoes" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_UbMmYC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_UbMmYS_rEe-kMoxTdsEtQg" type="JAVA_METHOD" expression="setJustificacoes">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Asby0x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Asby1B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Asby1R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Asby1x26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Asby1h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BTsAGR26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_D-gxeS_rEe-kMoxTdsEtQg" name="newForm1" content="a8ac3f8a-68bc-44b3-bc50-3b2cbaee4934" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BTsAGB26Ee-gZr0NkXqK5g">
            <inputs xmi:type="process:ContractInput" xmi:id="_UbL_QC_rEe-kMoxTdsEtQg" name="oportunidadeDeVendaInput" type="COMPLEX" dataReference="oportunidadeDeVenda" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_UbL_QS_rEe-kMoxTdsEtQg" name="descricao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UbL_Qi_rEe-kMoxTdsEtQg" name="solucao" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_UbL_Qy_rEe-kMoxTdsEtQg" name="justificacoes" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BTsAGx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1pDqkCliEe-hQaEMBNGyoA" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1pDqkSliEe-hQaEMBNGyoA" name="OportunidadeDeVenda.findByPersistenceId" content="SELECT o&#xA;FROM OportunidadeDeVenda o&#xA;WHERE o.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.OportunidadeDeVenda">
          <referencedElements xmi:type="expression:Expression" xmi:id="_wXZwsC21Ee-Fm89TGaDU3g" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_wXZwsS21Ee-Fm89TGaDU3g" name="1" content="1" returnType="java.lang.Long" returnTypeFixed="true"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_VqsdUDABEe-2xd8hzNmFeQ" name="emailMessage" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.EmailMessage">
        <defaultValue xmi:type="expression:Expression" xmi:id="_VqsdUTABEe-2xd8hzNmFeQ" name="EmailMessage.findByPersistenceId" content="SELECT e&#xA;FROM EmailMessage e&#xA;WHERE e.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.EmailMessage">
          <referencedElements xmi:type="expression:Expression" xmi:id="_I_MSoDDTEe-1LbipnKYqtw" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_I_MSoTDTEe-1LbipnKYqtw" name="1" content="1" returnType="java.lang.Long" returnTypeFixed="true"/>
          </referencedElements>
        </defaultValue>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_NmaqgDDVEe-1LbipnKYqtw" name="respostaFornecedor" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.Fornecedor">
        <defaultValue xmi:type="expression:Expression" xmi:id="_NmaqgTDVEe-1LbipnKYqtw" name="Fornecedor.findByPersistenceId" content="SELECT f&#xA;FROM Fornecedor f&#xA;WHERE f.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.Fornecedor">
          <referencedElements xmi:type="expression:Expression" xmi:id="_NmaqgjDVEe-1LbipnKYqtw" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_NmaqgzDVEe-1LbipnKYqtw" name="1" content="1" returnType="java.lang.Long" returnTypeFixed="true"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_MJpihB0JEe-wwLkYj99nvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_GXw_kjDiEe-BQ93tMzjnrA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_MJpihh0JEe-wwLkYj99nvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_MJpihx0JEe-wwLkYj99nvQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R5KPcB24Ee-gZr0NkXqK5g" target="_AxMDUCloEe-Q4N-lG7hnAQ" source="_QFJ7MB24Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R5K2gB24Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_R5K2gR24Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rmkBwB24Ee-gZr0NkXqK5g" name="não" target="_rmg-cB24Ee-gZr0NkXqK5g" source="_1b4EACl_Ee-Q4N-lG7hnAQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rmko0B24Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1JvLICl_Ee-Q4N-lG7hnAQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QDkxYB25Ee-gZr0NkXqK5g" target="_QDi8MB25Ee-gZr0NkXqK5g" source="__2TfECJ6Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QDkxYR25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_QDkxYh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aLA7cB25Ee-gZr0NkXqK5g" target="_e5Mh0B25Ee-gZr0NkXqK5g" source="_QDi8MB25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aLA7cR25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_aLA7ch25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tGo38B25Ee-gZr0NkXqK5g" target="_ty458B25Ee-gZr0NkXqK5g" source="_e5Mh0B25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tGo38R25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_tGo38h25Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AscZ4R26Ee-gZr0NkXqK5g" target="_BTrZAB26Ee-gZr0NkXqK5g" source="_7W0ZAB25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AscZ4h26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_AscZ4x26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IQ1YYB26Ee-gZr0NkXqK5g" target="_R-hlsB26Ee-gZr0NkXqK5g" source="_BTrZAB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IQ1YYR26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_IQ1YYh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_btmTEB26Ee-gZr0NkXqK5g" target="_dFCnIB26Ee-gZr0NkXqK5g" source="_R-hlsB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_btmTER26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_btmTEh26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-pDwYR26Ee-gZr0NkXqK5g" target="_QGn14ClgEe-TMIDnSmPP3w" source="_0eI0gB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-pEXcB26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_-pEXcR26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OxGK8x27Ee-gZr0NkXqK5g" target="_OxE80B27Ee-gZr0NkXqK5g" source="_Kl6j8B27Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OxGyAB27Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_OxGyAR27Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HCWPACJ7Ee-K9NOFx4MuYQ" target="_HCQvcCJ7Ee-K9NOFx4MuYQ" source="_AlWWYCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HCXdICJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HCXdISJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Odd8wCJ7Ee-K9NOFx4MuYQ" target="_OdcHkCJ7Ee-K9NOFx4MuYQ" source="_HCQvcCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Odd8wSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Odd8wiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XyX2oCJ7Ee-K9NOFx4MuYQ" target="_XyWBcCJ7Ee-K9NOFx4MuYQ" source="_CT_CcCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XyX2oSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XyX2oiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5bGgwCJ7Ee-K9NOFx4MuYQ" target="_Kl6j8B27Ee-gZr0NkXqK5g" source="_3-mtkCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5bGgwSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5bGgwiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DVNq0CleEe-TMIDnSmPP3w" target="_QFJ7MB24Ee-gZr0NkXqK5g" source="_Cy8EMCleEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DVNq0SleEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_DVNq0ileEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uJbXoClfEe-TMIDnSmPP3w" target="_2S3j8ClfEe-TMIDnSmPP3w" source="_OxE80B27Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uJbXoSlfEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_uJbXoilfEe-TMIDnSmPP3w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_unGLEClfEe-TMIDnSmPP3w" target="_WeqLcClfEe-TMIDnSmPP3w" source="_2S3j8ClfEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_unGyIClfEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_unGyISlfEe-TMIDnSmPP3w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ca_U8C2VEe-1jpJFqdf7Ng" target="_7W0ZAB25Ee-gZr0NkXqK5g" source="_ty458B25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ca_U8S2VEe-1jpJFqdf7Ng"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ca_U8i2VEe-1jpJFqdf7Ng" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f5VYUC5QEe-LUL3cchlqMw" target="_1b4EACl_Ee-Q4N-lG7hnAQ" source="_AxMDUCloEe-Q4N-lG7hnAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f5X0kC5QEe-LUL3cchlqMw"/>
        <condition xmi:type="expression:Expression" xmi:id="_f5YboC5QEe-LUL3cchlqMw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_UrrTcC5YEe-SvPntKcWM0A" name="sim" target="_60Yv4C5YEe-SvPntKcWM0A" source="_1b4EACl_Ee-Q4N-lG7hnAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_UrtIoC5YEe-SvPntKcWM0A"/>
        <condition xmi:type="expression:Expression" xmi:id="_UrtIoS5YEe-SvPntKcWM0A" name="newScript()" content="oportunidadeDeVenda.tipo_ov == 'venda_de_solucoes';" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Mg8-oDDSEe-1LbipnKYqtw" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_VdntwC5YEe-SvPntKcWM0A" target="__2TfECJ6Ee-K9NOFx4MuYQ" source="_60Yv4C5YEe-SvPntKcWM0A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Vdr_MC5YEe-SvPntKcWM0A"/>
        <condition xmi:type="expression:Expression" xmi:id="_VdsmQC5YEe-SvPntKcWM0A" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aRYhIC_sEe-kMoxTdsEtQg" target="_0eI0gB26Ee-gZr0NkXqK5g" source="_dFCnIB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aRdZoC_sEe-kMoxTdsEtQg"/>
        <condition xmi:type="expression:Expression" xmi:id="_aRdZoS_sEe-kMoxTdsEtQg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_c9HkMDDUEe-1LbipnKYqtw" target="_iVrdUCJ7Ee-K9NOFx4MuYQ" source="_QGn14ClgEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_c9HkMTDUEe-1LbipnKYqtw"/>
        <condition xmi:type="expression:Expression" xmi:id="_c9HkMjDUEe-1LbipnKYqtw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w7x1kDDVEe-1LbipnKYqtw" target="_38oCIDDVEe-1LbipnKYqtw" source="_iVrdUCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w7x1kTDVEe-1LbipnKYqtw"/>
        <condition xmi:type="expression:Expression" xmi:id="_w7x1kjDVEe-1LbipnKYqtw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_xJ8NYDDVEe-1LbipnKYqtw" target="_Kl6j8B27Ee-gZr0NkXqK5g" source="_38oCIDDVEe-1LbipnKYqtw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_xJ80cDDVEe-1LbipnKYqtw"/>
        <condition xmi:type="expression:Expression" xmi:id="_xJ80cTDVEe-1LbipnKYqtw" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="__SWrMCJ_Ee-hF5ts4rL8SA" name="Equipa Técnica"/>
      <actors xmi:type="process:Actor" xmi:id="_IfqIQCKAEe-hF5ts4rL8SA" name="Gestor da OV" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_NiFgUCKAEe-hF5ts4rL8SA" name="Serviços de Apoio ao Negócio (área logística)"/>
      <actors xmi:type="process:Actor" xmi:id="_VVkDsCKAEe-hF5ts4rL8SA" name="Serviços de Apoio ao Negócio (área comercial)"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_4BLc4CmAEe-Q4N-lG7hnAQ" name="Production" version="8" username="william.jobs">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_4BMD8CmAEe-Q4N-lG7hnAQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD8SmAEe-Q4N-lG7hnAQ" name="Equipa Técnica">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD8imAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD8ymAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD9CmAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD9SmAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD9imAEe-Q4N-lG7hnAQ" name="Gestor da OV">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD9ymAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD-CmAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD-SmAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD-imAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD-ymAEe-Q4N-lG7hnAQ" name="Serviços de Apoio ao Negócio (área logística)">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD_CmAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD_SmAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD_imAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD_ymAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMEACmAEe-Q4N-lG7hnAQ" name="Serviços de Apoio ao Negócio (área comercial)">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMEASmAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMEAimAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMEAymAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMEBCmAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_4BLc4SmAEe-Q4N-lG7hnAQ" type="ACTOR_FILTER" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0" implementationId="bonita-actorfilter-initiator-impl" implementationVersion="1.0.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_D_Zs8CmCEe-Q4N-lG7hnAQ" type="CONNECTOR" definitionId="email" definitionVersion="1.2.0" implementationId="email-impl" implementationVersion="1.4.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc4imAEe-Q4N-lG7hnAQ" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_EC5F0CmCEe-Q4N-lG7hnAQ" id="email-impl-1.4.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_EC9XQCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="bonita-connector-email-1.4.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_EC_zgCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="jakarta.mail-1.6.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_EDCPwCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="jakarta.mail-api-1.6.7.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc4ymAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5CmAEe-Q4N-lG7hnAQ" id="ACTOR_FILTER">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5SmAEe-Q4N-lG7hnAQ" id="bonita-actorfilter-initiator-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_4BLc5imAEe-Q4N-lG7hnAQ" key="bonita-actorfilter-initiator-impl -- 1.0.0" value="bonita-actorfilter-initiator-1.0.0.jar" type="ACTOR_FILTER"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5ymAEe-Q4N-lG7hnAQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc6CmAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_MJpijB0JEe-wwLkYj99nvQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpijR0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpijh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpijx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpikB0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpikR0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpikh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpikx0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpilB0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpilR0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpilh0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpilx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpimB0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpimR0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpimh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpimx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_uad6UCJ6Ee-K9NOFx4MuYQ" name="Pool1">
      <formMapping xmi:type="process:FormMapping" xmi:id="_ufT-ECJ6Ee-K9NOFx4MuYQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_GYq-gDDiEe-BQ93tMzjnrA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ufT-EiJ6Ee-K9NOFx4MuYQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ufT-EyJ6Ee-K9NOFx4MuYQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <configurations xmi:type="configuration:Configuration" xmi:id="_4HA_ICmAEe-Q4N-lG7hnAQ" name="Production" version="8" username="william.jobs">
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_ISmAEe-Q4N-lG7hnAQ" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_IimAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_IymAEe-Q4N-lG7hnAQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_JCmAEe-Q4N-lG7hnAQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_JSmAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_ufT-FCJ6Ee-K9NOFx4MuYQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpUCJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpUSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpUiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpUyJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpVCJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpVSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpViJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpVyJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpWCJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpWSJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpWiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpWyJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpXCJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpXSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpXiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_MJpinB0JEe-wwLkYj99nvQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_MJpinR0JEe-wwLkYj99nvQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_MJpinh0JEe-wwLkYj99nvQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_MJpinx0JEe-wwLkYj99nvQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_MJpioB0JEe-wwLkYj99nvQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_MJpioR0JEe-wwLkYj99nvQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_MJpioh0JEe-wwLkYj99nvQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_MJpiox0JEe-wwLkYj99nvQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_MJpipB0JEe-wwLkYj99nvQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_MJpipR0JEe-wwLkYj99nvQ" type="Process" element="_MJpicB0JEe-wwLkYj99nvQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_uf07cCJ6Ee-K9NOFx4MuYQ" type="2007" element="_uad6UCJ6Ee-K9NOFx4MuYQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_uf2JkCJ6Ee-K9NOFx4MuYQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_uf2woCJ6Ee-K9NOFx4MuYQ" type="7001"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_uf07cSJ6Ee-K9NOFx4MuYQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_uf07ciJ6Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_uf07cyJ6Ee-K9NOFx4MuYQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_uf2woSJ6Ee-K9NOFx4MuYQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uf07dCJ6Ee-K9NOFx4MuYQ" width="1470" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_MJpiph0JEe-wwLkYj99nvQ" type="2007" element="_MJpicR0JEe-wwLkYj99nvQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_MJpipx0JEe-wwLkYj99nvQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqB0JEe-wwLkYj99nvQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_MJpiqR0JEe-wwLkYj99nvQ" type="3007" element="_MJpich0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqh0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqx0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_QGTxwB24Ee-gZr0NkXqK5g" type="3027" element="_QFJ7MB24Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QGU_4B24Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QGTxwR24Ee-gZr0NkXqK5g" x="160" y="60" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rmiMkB24Ee-gZr0NkXqK5g" type="3003" element="_rmg-cB24Ee-gZr0NkXqK5g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rmizoB24Ee-gZr0NkXqK5g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rmizoR24Ee-gZr0NkXqK5g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rmiMkR24Ee-gZr0NkXqK5g" x="1166" y="21"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QDkKUB25Ee-gZr0NkXqK5g" type="3027" element="_QDi8MB25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QDkKUh25Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QDkKUR25Ee-gZr0NkXqK5g" x="702" y="61" width="181" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_e5Nv8B25Ee-gZr0NkXqK5g" type="3005" element="_e5Mh0B25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_e5Nv8h25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e5Nv8R25Ee-gZr0NkXqK5g" x="860" y="179" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R-iMyh26Ee-gZr0NkXqK5g" type="3005" element="_R-hlsB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_R-iz0B26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R-iMyx26Ee-gZr0NkXqK5g" x="1277" y="151" width="164" height="82"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Kl7LCB27Ee-gZr0NkXqK5g" type="3027" element="_Kl6j8B27Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Kl7LCh27Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Kl7LCR27Ee-gZr0NkXqK5g" x="2208" y="144" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OxGK8B27Ee-gZr0NkXqK5g" type="3027" element="_OxE80B27Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OxGK8h27Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OxGK8R27Ee-gZr0NkXqK5g" x="2417" y="143" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__2UtMCJ6Ee-K9NOFx4MuYQ" type="3005" element="__2TfECJ6Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__2UtMiJ6Ee-K9NOFx4MuYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_AlYLkCJ7Ee-K9NOFx4MuYQ" type="3064" element="_AlWWYCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_AlYLkiJ7Ee-K9NOFx4MuYQ" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_AlYyoCJ7Ee-K9NOFx4MuYQ" x="-24" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AlYLkSJ7Ee-K9NOFx4MuYQ"/>
              </children>
              <children xmi:type="notation:Shape" xmi:id="_CUAQkCJ7Ee-K9NOFx4MuYQ" type="3043" element="_CT_CcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_CUAQkiJ7Ee-K9NOFx4MuYQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_CUAQkyJ7Ee-K9NOFx4MuYQ" x="56" y="-3"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CUAQkSJ7Ee-K9NOFx4MuYQ" x="90" y="62"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__2UtMSJ6Ee-K9NOFx4MuYQ" x="500" y="136" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HCR9kCJ7Ee-K9NOFx4MuYQ" type="3027" element="_HCQvcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HCR9kiJ7Ee-K9NOFx4MuYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HCR9kSJ7Ee-K9NOFx4MuYQ" x="463" y="346" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OdcuoyJ7Ee-K9NOFx4MuYQ" type="3003" element="_OdcHkCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OddVsCJ7Ee-K9NOFx4MuYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OddVsSJ7Ee-K9NOFx4MuYQ" x="21" y="27"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OdcupCJ7Ee-K9NOFx4MuYQ" x="638" y="301"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XyWogyJ7Ee-K9NOFx4MuYQ" type="3003" element="_XyWBcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XyXPkCJ7Ee-K9NOFx4MuYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XyXPkSJ7Ee-K9NOFx4MuYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XyWohCJ7Ee-K9NOFx4MuYQ" x="734" y="228"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iVugoCJ7Ee-K9NOFx4MuYQ" type="3005" element="_iVrdUCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iVvHsCJ7Ee-K9NOFx4MuYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_3-n7sCJ7Ee-K9NOFx4MuYQ" type="3043" element="_3-mtkCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_3-n7siJ7Ee-K9NOFx4MuYQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_3-n7syJ7Ee-K9NOFx4MuYQ" x="-33" y="15"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3-n7sSJ7Ee-K9NOFx4MuYQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iVugoSJ7Ee-K9NOFx4MuYQ" x="1847" y="156" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Cy95YCleEe-TMIDnSmPP3w" type="3002" element="_Cy8EMCleEe-TMIDnSmPP3w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Cy95YileEe-TMIDnSmPP3w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Cy95YyleEe-TMIDnSmPP3w" x="2" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cy95YSleEe-TMIDnSmPP3w" x="74" y="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WerZkClfEe-TMIDnSmPP3w" type="3003" element="_WeqLcClfEe-TMIDnSmPP3w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WerZkilfEe-TMIDnSmPP3w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WerZkylfEe-TMIDnSmPP3w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WerZkSlfEe-TMIDnSmPP3w" x="2797" y="171"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2S4LCClfEe-TMIDnSmPP3w" type="3027" element="_2S3j8ClfEe-TMIDnSmPP3w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2S4LCilfEe-TMIDnSmPP3w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2S4LCSlfEe-TMIDnSmPP3w" x="2607" y="150" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QGoc_ClgEe-TMIDnSmPP3w" type="3005" element="_QGn14ClgEe-TMIDnSmPP3w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QGoc_ilgEe-TMIDnSmPP3w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QGoc_SlgEe-TMIDnSmPP3w" x="1619" y="150" width="192" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AxMqaCloEe-Q4N-lG7hnAQ" type="3027" element="_AxMDUCloEe-Q4N-lG7hnAQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AxMqailoEe-Q4N-lG7hnAQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AxMqaSloEe-Q4N-lG7hnAQ" x="159" y="160" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1b4rECl_Ee-Q4N-lG7hnAQ" type="3008" element="_1b4EACl_Ee-Q4N-lG7hnAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1b4rEil_Ee-Q4N-lG7hnAQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1b4rEyl_Ee-Q4N-lG7hnAQ" x="153" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1b4rESl_Ee-Q4N-lG7hnAQ" x="368" y="60" width="41" height="41"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_60uHEC5YEe-SvPntKcWM0A" type="3027" element="_60Yv4C5YEe-SvPntKcWM0A" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_60zmoC5YEe-SvPntKcWM0A" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_60uuIC5YEe-SvPntKcWM0A" x="345" y="145" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_38opPDDVEe-1LbipnKYqtw" type="3005" element="_38oCIDDVEe-1LbipnKYqtw" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_38pQQDDVEe-1LbipnKYqtw" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_38opPTDVEe-1LbipnKYqtw" x="2018" y="161" width="140" height="70"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_MJpisx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_MJpitB0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_MJpitR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_MJpith0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MJpitx0JEe-wwLkYj99nvQ" x="28" y="10" width="2514" height="478"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VE1UwB0JEe-wwLkYj99nvQ" type="3007" element="_VEyRcB0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VE170B0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VE170R0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ty6IEB25Ee-gZr0NkXqK5g" type="3005" element="_ty458B25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ty6IEh25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ty6IER25Ee-gZr0NkXqK5g" x="833" y="23" width="219" height="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dFDOOR26Ee-gZr0NkXqK5g" type="3005" element="_dFCnIB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dFD1QB26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dFDOOh26Ee-gZr0NkXqK5g" x="1277" y="29" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0eJblx26Ee-gZr0NkXqK5g" type="3005" element="_0eI0gB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0eJbmR26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0eJbmB26Ee-gZr0NkXqK5g" x="1619" y="30" width="191" height="95"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VE1UwR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VE1Uwh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VE1Uwx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VE170h0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VE1UxB0JEe-wwLkYj99nvQ" x="53" y="478" width="2578" height="184"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VTv6gB0JEe-wwLkYj99nvQ" type="3007" element="_VTusYB0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VTv6hR0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VTv6hh0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_7W2OMR25Ee-gZr0NkXqK5g" type="3005" element="_7W0ZAB25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7W2OMx25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7W2OMh25Ee-gZr0NkXqK5g" x="837" y="46" width="212" height="106"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VTv6gR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VTv6gh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VTv6gx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VTwhkB0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VTv6hB0JEe-wwLkYj99nvQ" x="33" y="662" width="2851" height="209"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VkxZEB0JEe-wwLkYj99nvQ" type="3007" element="_Vkvj4B0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VkyAIB0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VkyAIR0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_BTsnIB26Ee-gZr0NkXqK5g" type="3005" element="_BTrZAB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BTsnIh26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BTsnIR26Ee-gZr0NkXqK5g" x="841" y="32" width="204" height="102"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VkxZER0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VkxZEh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VkxZEx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VkyAIh0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VkxZFB0JEe-wwLkYj99nvQ" x="33" y="871" width="2851" height="194"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_MJpiuB0JEe-wwLkYj99nvQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_MJpiuR0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_MJpiuh0JEe-wwLkYj99nvQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_MJpiux0JEe-wwLkYj99nvQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MJpivB0JEe-wwLkYj99nvQ" width="2960" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_MJpivR0JEe-wwLkYj99nvQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_R5MEoB24Ee-gZr0NkXqK5g" type="4001" element="_R5KPcB24Ee-gZr0NkXqK5g" source="_QGTxwB24Ee-gZr0NkXqK5g" target="_AxMqaCloEe-Q4N-lG7hnAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R5MrsB24Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R5NSwB24Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R5MEoR24Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R5MEoh24Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rmlP4B24Ee-gZr0NkXqK5g" type="4001" element="_rmkBwB24Ee-gZr0NkXqK5g" source="_1b4rECl_Ee-Q4N-lG7hnAQ" target="_rmiMkB24Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rml28B24Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rml28R24Ee-gZr0NkXqK5g" x="-352" y="-7"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rmlP4R24Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rmlP4h24Ee-gZr0NkXqK5g" points="[0, -21, -789, 27]$[0, -49, -789, -1]$[774, -49, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QDlYcB25Ee-gZr0NkXqK5g" type="4001" element="_QDkxYB25Ee-gZr0NkXqK5g" source="__2UtMCJ6Ee-K9NOFx4MuYQ" target="_QDkKUB25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QDlYcx25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QDlYdB25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QDlYcR25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QDlYch25Ee-gZr0NkXqK5g" points="[60, -1, -132, 90]$[96, -1, -96, 90]$[96, -93, -96, -2]$[142, -93, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aLA7cx25Ee-gZr0NkXqK5g" type="4001" element="_aLA7cB25Ee-gZr0NkXqK5g" source="_QDkKUB25Ee-gZr0NkXqK5g" target="_e5Nv8B25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aLBigB25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aLBigR25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aLA7dB25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aLA7dR25Ee-gZr0NkXqK5g" points="[91, 0, -51, -110]$[134, 0, -8, -110]$[134, 73, -8, -37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tGo38x25Ee-gZr0NkXqK5g" type="4001" element="_tGo38B25Ee-gZr0NkXqK5g" source="_e5Nv8B25Ee-gZr0NkXqK5g" target="_ty6IEB25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tGo39h25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tGpfAB25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tGo39B25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tGo39R25Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AsdA8B26Ee-gZr0NkXqK5g" type="4001" element="_AscZ4R26Ee-gZr0NkXqK5g" source="_7W2OMR25Ee-gZr0NkXqK5g" target="_BTsnIB26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AsdA8x26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AsdA9B26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AsdA8R26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AsdA8h26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IQ1YYx26Ee-gZr0NkXqK5g" type="4001" element="_IQ1YYB26Ee-gZr0NkXqK5g" source="_BTsnIB26Ee-gZr0NkXqK5g" target="_R-iMyh26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IQ1_cB26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IQ1_cR26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IQ1YZB26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IQ1YZR26Ee-gZr0NkXqK5g" points="[77, 2, -115, 695]$[105, 2, -87, 695]$[105, -694, -87, -1]$[132, -694, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_btm6IB26Ee-gZr0NkXqK5g" type="4001" element="_btmTEB26Ee-gZr0NkXqK5g" source="_R-iMyh26Ee-gZr0NkXqK5g" target="_dFDOOR26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_btm6Ix26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_btm6JB26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_btm6IR26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_btm6Ih26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-pEXch26Ee-gZr0NkXqK5g" type="4001" element="_-pDwYR26Ee-gZr0NkXqK5g" source="_0eJblx26Ee-gZr0NkXqK5g" target="_QGoc_ClgEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-pEXdR26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-pEXdh26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-pEXcx26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-pEXdB26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OxGyAh27Ee-gZr0NkXqK5g" type="4001" element="_OxGK8x27Ee-gZr0NkXqK5g" source="_Kl7LCB27Ee-gZr0NkXqK5g" target="_OxGK8B27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OxGyBR27Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OxGyBh27Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OxGyAx27Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OxGyBB27Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HCYEMCJ7Ee-K9NOFx4MuYQ" type="4001" element="_HCWPACJ7Ee-K9NOFx4MuYQ" source="_AlYLkCJ7Ee-K9NOFx4MuYQ" target="_HCR9kCJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HCZSUCJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HCZSUSJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HCYrQCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HCYrQSJ7Ee-K9NOFx4MuYQ" points="[-2, 13, -1, -92]$[-2, 70, -1, -35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Odej0CJ7Ee-K9NOFx4MuYQ" type="4001" element="_Odd8wCJ7Ee-K9NOFx4MuYQ" source="_HCR9kCJ7Ee-K9NOFx4MuYQ" target="_OdcuoyJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Odej0yJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Odej1CJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Odej0SJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Odej0iJ7Ee-K9NOFx4MuYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XyX2oyJ7Ee-K9NOFx4MuYQ" type="4001" element="_XyX2oCJ7Ee-K9NOFx4MuYQ" source="_CUAQkCJ7Ee-K9NOFx4MuYQ" target="_XyWogyJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XyYdsCJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XyYdsSJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XyX2pCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XyX2pSJ7Ee-K9NOFx4MuYQ" points="[0, 13, -147, -20]$[0, 32, -147, -1]$[132, 32, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5bHu4CJ7Ee-K9NOFx4MuYQ" type="4001" element="_5bGgwCJ7Ee-K9NOFx4MuYQ" source="_3-n7sCJ7Ee-K9NOFx4MuYQ" target="_Kl7LCB27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5bHu4yJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5bHu5CJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5bHu4SJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5bHu4iJ7Ee-K9NOFx4MuYQ" points="[-13, 0, -212, 9]$[-13, 29, -212, 38]$[208, 29, 9, 38]$[208, -5, 9, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5bKyMCJ7Ee-K9NOFx4MuYQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5bKyMSJ7Ee-K9NOFx4MuYQ" id="(0.44642857142857145,0.9523809523809523)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DVOR4CleEe-TMIDnSmPP3w" type="4001" element="_DVNq0CleEe-TMIDnSmPP3w" source="_Cy95YCleEe-TMIDnSmPP3w" target="_QGTxwB24Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DVOR4yleEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DVOR5CleEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DVOR4SleEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DVOR4ileEe-TMIDnSmPP3w" points="[-5, -26, -103, 7]$[85, -26, -13, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DVPgACleEe-TMIDnSmPP3w" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DVPgASleEe-TMIDnSmPP3w" id="(0.13,0.34)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uJb-sClfEe-TMIDnSmPP3w" type="4001" element="_uJbXoClfEe-TMIDnSmPP3w" source="_OxGK8B27Ee-gZr0NkXqK5g" target="_2S4LCClfEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uJb-sylfEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uJb-tClfEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uJb-sSlfEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uJb-silfEe-TMIDnSmPP3w" points="[0, 2, -79, 0]$[54, -1, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uJdM0ClfEe-TMIDnSmPP3w" id="(1.0,0.4266666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uJdM0SlfEe-TMIDnSmPP3w" id="(0.1736111111111111,0.4444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_unGyIilfEe-TMIDnSmPP3w" type="4001" element="_unGLEClfEe-TMIDnSmPP3w" source="_2S4LCClfEe-TMIDnSmPP3w" target="_WerZkClfEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_unHZMClfEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_unHZMSlfEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_unGyIylfEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_unGyJClfEe-TMIDnSmPP3w" points="[0, 8, -61, -3]$[46, 8, -15, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_unIAQClfEe-TMIDnSmPP3w" id="(1.0,0.3472222222222222)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ca_8AC2VEe-1jpJFqdf7Ng" type="4001" element="_Ca_U8C2VEe-1jpJFqdf7Ng" source="_ty6IEB25Ee-gZr0NkXqK5g" target="_7W2OMR25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ca_8Ay2VEe-1jpJFqdf7Ng" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ca_8BC2VEe-1jpJFqdf7Ng" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ca_8AS2VEe-1jpJFqdf7Ng" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca_8Ai2VEe-1jpJFqdf7Ng" points="[0, 0, -136, -191]$[217, 196, 81, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CbC_UC2VEe-1jpJFqdf7Ng" id="(0.5283018867924528,0.9873417721518988)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f5aQ0C5QEe-LUL3cchlqMw" type="4001" element="_f5VYUC5QEe-LUL3cchlqMw" source="_AxMqaCloEe-Q4N-lG7hnAQ" target="_1b4rECl_Ee-Q4N-lG7hnAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f5a34C5QEe-LUL3cchlqMw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f5a34S5QEe-LUL3cchlqMw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f5aQ0S5QEe-LUL3cchlqMw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f5aQ0i5QEe-LUL3cchlqMw" points="[0, 0, -89, 104]$[89, -105, 0, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f5cGAC5QEe-LUL3cchlqMw" id="(1.0,0.43333333333333335)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f5cGAS5QEe-LUL3cchlqMw" id="(0.0,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UruWwC5YEe-SvPntKcWM0A" type="4001" element="_UrrTcC5YEe-SvPntKcWM0A" source="_1b4rECl_Ee-Q4N-lG7hnAQ" target="_60uHEC5YEe-SvPntKcWM0A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UrwL8C5YEe-SvPntKcWM0A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UrwL8S5YEe-SvPntKcWM0A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UruWwS5YEe-SvPntKcWM0A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UruWwi5YEe-SvPntKcWM0A" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Vdys4C5YEe-SvPntKcWM0A" type="4001" element="_VdntwC5YEe-SvPntKcWM0A" source="_60uHEC5YEe-SvPntKcWM0A" target="__2UtMCJ6Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Vd0iEC5YEe-SvPntKcWM0A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Vd1wMC5YEe-SvPntKcWM0A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Vdys4S5YEe-SvPntKcWM0A" fontName=".AppleSystemUIFont"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Vdys4i5YEe-SvPntKcWM0A" points="[0, 0, -56, 0]$[50, 0, -6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VeBWYC5YEe-SvPntKcWM0A" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_VeBWYS5YEe-SvPntKcWM0A" id="(0.03571428571428571,0.5142857142857142)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aRiSIC_sEe-kMoxTdsEtQg" type="4001" element="_aRYhIC_sEe-kMoxTdsEtQg" source="_dFDOOR26Ee-gZr0NkXqK5g" target="_0eJblx26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aRi5MC_sEe-kMoxTdsEtQg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aRi5MS_sEe-kMoxTdsEtQg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aRiSIS_sEe-kMoxTdsEtQg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aRiSIi_sEe-kMoxTdsEtQg" points="[0, -4, -209, 1]$[209, -18, 0, -13]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aRnKoC_sEe-kMoxTdsEtQg" id="(1.0,0.39285714285714285)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_aRnKoS_sEe-kMoxTdsEtQg" id="(0.14659685863874344,0.17894736842105263)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_c9ILQDDUEe-1LbipnKYqtw" type="4001" element="_c9HkMDDUEe-1LbipnKYqtw" source="_QGoc_ClgEe-TMIDnSmPP3w" target="_iVugoCJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_c9ILQzDUEe-1LbipnKYqtw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_c9IyUDDUEe-1LbipnKYqtw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_c9ILQTDUEe-1LbipnKYqtw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_c9ILQjDUEe-1LbipnKYqtw" points="[-96, -29, -198, 34]$[-96, -77, -198, -14]$[74, -77, -28, -14]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_c9KAcDDUEe-1LbipnKYqtw" id="(1.0,0.3020833333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_c9KAcTDUEe-1LbipnKYqtw" id="(0.23333333333333334,0.7166666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w7ycoDDVEe-1LbipnKYqtw" type="4001" element="_w7x1kDDVEe-1LbipnKYqtw" source="_iVugoCJ7Ee-K9NOFx4MuYQ" target="_38opPDDVEe-1LbipnKYqtw" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w7ycozDVEe-1LbipnKYqtw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w7ycpDDVEe-1LbipnKYqtw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w7ycoTDVEe-1LbipnKYqtw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w7ycojDVEe-1LbipnKYqtw" points="[0, 3, -121, -7]$[51, 3, -70, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_w7zqwDDVEe-1LbipnKYqtw" id="(1.0,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_xJ80cjDVEe-1LbipnKYqtw" type="4001" element="_xJ8NYDDVEe-1LbipnKYqtw" source="_38opPDDVEe-1LbipnKYqtw" target="_Kl7LCB27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_xJ9bgDDVEe-1LbipnKYqtw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_xJ9bgTDVEe-1LbipnKYqtw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_xJ80czDVEe-1LbipnKYqtw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_xJ80dDDVEe-1LbipnKYqtw" points="[0, -12, -76, 6]$[50, -12, -26, 6]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xJ-CkDDVEe-1LbipnKYqtw" id="(1.0,0.64)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xJ-CkTDVEe-1LbipnKYqtw" id="(0.15476190476190477,0.5119047619047619)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
