<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:actormapping="http://www.bonitasoft.org/ns/actormapping/6.0" xmlns:configuration="http://www.bonitasoft.org/ns/bpm/configuration" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_MJpicB0JEe-wwLkYj99nvQ" name="Conceber_solucao" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_MJpicR0JEe-wwLkYj99nvQ" name="Conceber a Solução">
      <elements xmi:type="process:Lane" xmi:id="_MJpich0JEe-wwLkYj99nvQ" name="Gestor OV" actor="_IfqIQCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:ServiceTask" xmi:id="_QFJ7MB24Ee-gZr0NkXqK5g" name="Carregar OV" outgoing="_R5KPcB24Ee-gZr0NkXqK5g" incoming="_DVNq0CleEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_MJpieB0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_MJpieR0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_MJpieh0JEe-wwLkYj99nvQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_MJpiex0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_MJpifB0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_MJpifR0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_MJpifh0JEe-wwLkYj99nvQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_MJpifx0JEe-wwLkYj99nvQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_rmg-cB24Ee-gZr0NkXqK5g" name="Solução cancelada, não é uma venda de solução" incoming="_rmkBwB24Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_rmhlgR24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_rmhlgB24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_rmhlgh24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_QDi8MB25Ee-gZr0NkXqK5g" name="Carregar e respeitar &quot;Catálogo de Serviço  da empresa&quot;" outgoing="_aLA7cB25Ee-gZr0NkXqK5g" incoming="_QDkxYB25Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QDjjQR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QDjjQB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QDjjQh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QDjjQx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QDjjRB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QDjjRR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QDjjRx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QDjjRh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_e5Mh0B25Ee-gZr0NkXqK5g" name="Conceção da solução" outgoing="_tGo38B25Ee-gZr0NkXqK5g" incoming="_aLA7cB25Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_aK_tUR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_aK_tUB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_aK_tUh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_aK_tUx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_aK_tVB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_aK_tVR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_aK_tVx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_aK_tVh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_e5NI6R25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_9nHmMSPkEe-u9q7LyKFNBA" name="conceberSolucao" content="09da9cf7-63d9-4d57-a334-96e31642941c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_e5NI6B25Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_e5NI6x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_R-hlsB26Ee-gZr0NkXqK5g" name="Conceber melhor solução para o cliente" outgoing="_btmTEB26Ee-gZr0NkXqK5g" incoming="_IQ1YYB26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_IQ0KQh26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_IQ0KQR26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_IQ0KQx26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_IQ0KRB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_IQ0KRR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_IQ0KRh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_IQ0KSB26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_IQ0KRx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_R-iMxx26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6EC22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_R-iMxh26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_R-iMyR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_m5SIYB26Ee-gZr0NkXqK5g" name="Elaborar justificações" outgoing="_st1g8B26Ee-gZr0NkXqK5g" incoming="_jBRVAB26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_jBQt8B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_jBQG4R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_jBQt8R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_jBQt8h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_jBQt8x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_jBQt9B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_jBQt9h26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_jBQt9R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_m5SveR26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6ES22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_m5SveB26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_m5Svex26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Kl6j8B27Ee-gZr0NkXqK5g" name="Associar solução à OV" outgoing="_OxGK8x27Ee-gZr0NkXqK5g" incoming="_Kl7yEB27Ee-gZr0NkXqK5g _5bGgwCJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Kl7LAR27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Kl7LAB27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Kl7LAh27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Kl7LAx27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Kl7LBB27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Kl7LBR27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Kl7LBx27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Kl7LBh27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_OxE80B27Ee-gZr0NkXqK5g" name="Guadar OV no CRM" outgoing="_uJbXoClfEe-TMIDnSmPP3w" incoming="_OxGK8x27Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OxFj4R27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OxFj4B27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OxFj4h27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_OxFj4x27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_OxFj5B27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_OxFj5R27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_OxFj5x27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_OxFj5h27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="__2TfECJ6Ee-K9NOFx4MuYQ" name="Retorno dos requisitos" outgoing="_QDkxYB25Ee-gZr0NkXqK5g" incoming="_L5jA8B25Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L5hy0R25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L5hy0B25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L5hy0h25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L5hy0x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L5hy1B25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L5hy1R25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L5hy1x25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L5hy1h25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_AlWWYCJ7Ee-K9NOFx4MuYQ" name="1 dia" outgoing="_HCWPACJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_cBwvAClcEe-TMIDnSmPP3w" name="1 Days 00:00:00" content="86400000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_CT_CcCJ7Ee-K9NOFx4MuYQ" name="7 dias" outgoing="_XyX2oCJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_WRNFoClcEe-TMIDnSmPP3w" name="7 Days 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="__2UGKSJ6Ee-K9NOFx4MuYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6Ei22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="__2UGKCJ6Ee-K9NOFx4MuYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="__2UGKyJ6Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_HCQvcCJ7Ee-K9NOFx4MuYQ" name="Notificar cliente acerca dos requisitos" outgoing="_Odd8wCJ7Ee-K9NOFx4MuYQ" incoming="_HCWPACJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HCRWgSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HCRWgCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HCRWgiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HCRWgyJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HCRWhCJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HCRWhSJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HCRWhyJ7Ee-K9NOFx4MuYQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HCRWhiJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_OdcHkCJ7Ee-K9NOFx4MuYQ" name="Cliente Notificado" incoming="_Odd8wCJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_OdcuoSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_OdcuoCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_OdcuoiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_XyWBcCJ7Ee-K9NOFx4MuYQ" name="Concessão cancelada, sem resposta do cliente" incoming="_XyX2oCJ7Ee-K9NOFx4MuYQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XyWogSJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XyWogCJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XyWogiJ7Ee-K9NOFx4MuYQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_iVrdUCJ7Ee-K9NOFx4MuYQ" name="Retorno do fornecedor" outgoing="_Kl7yEB27Ee-gZr0NkXqK5g" incoming="_BVbQAB27Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BVZa0h27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BVZa0R27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BVZa0x27Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BVZa1B27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BVZa1R27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BVZa1h27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BVZa2B27Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BVZa1x27Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_3-mtkCJ7Ee-K9NOFx4MuYQ" name="apos 7 dias" outgoing="_5bGgwCJ7Ee-K9NOFx4MuYQ">
            <condition xmi:type="expression:Expression" xmi:id="_mr0IECPkEe-u9q7LyKFNBA" name="7 Days 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_iVtSgiJ7Ee-K9NOFx4MuYQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6Ey22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_iVtSgSJ7Ee-K9NOFx4MuYQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_iVtShCJ7Ee-K9NOFx4MuYQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:StartEvent" xmi:id="_Cy8EMCleEe-TMIDnSmPP3w" name="Conceber solução" outgoing="_DVNq0CleEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Cy8EMileEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Cy8EMSleEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Cy8EMyleEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_WeqLcClfEe-TMIDnSmPP3w" name="Solução concebida com sucesso" incoming="_unGLEClfEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_WeqygSlfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_WeqygClfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_WeqygilfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_2S3j8ClfEe-TMIDnSmPP3w" name="Gerar solução em pdf" outgoing="_unGLEClfEe-TMIDnSmPP3w" incoming="_uJbXoClfEe-TMIDnSmPP3w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_by-kwSlfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_by-kwClfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_by-kwilfEe-TMIDnSmPP3w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_by-kwylfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_by-kxClfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_by-kxSlfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_by-kxylfEe-TMIDnSmPP3w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_by-kxilfEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QGn14ClgEe-TMIDnSmPP3w" name="Contactar fornecedores (preços/prazos/condições de entrega)" outgoing="_BVbQAB27Ee-gZr0NkXqK5g" incoming="_-pDwYR26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_-pDJUR26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_-pDJUB26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_-pDJUh26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_-pDJUx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_-pDJVB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_-pDJVR26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_-pDJVx26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_-pDJVh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QGoc-SlgEe-TMIDnSmPP3w">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6FC22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QGoc-ClgEe-TMIDnSmPP3w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QGoc-ylgEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_AxMDUCloEe-Q4N-lG7hnAQ" name="Verificar tipo de OV" outgoing="_6mBvkC2vEe-Fm89TGaDU3g" incoming="_R5KPcB24Ee-gZr0NkXqK5g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_R5DhwR24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_R5DhwB24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_R5Dhwh24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_R5Dhwx24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_R5DhxB24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_R5DhxR24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_R5Dhxx24Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_R5Dhxh24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1b4EACl_Ee-Q4N-lG7hnAQ" name="Tipo de OV &quot;venda de soluções&quot;?" outgoing="_rmkBwB24Ee-gZr0NkXqK5g _fNbikC22Ee-Fm89TGaDU3g" incoming="_7e9isC2vEe-Fm89TGaDU3g">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZmFe4R24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZmFe4B24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZmFe4h24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_5JaAkC2vEe-Fm89TGaDU3g" name="Step1" outgoing="_7e9isC2vEe-Fm89TGaDU3g" incoming="_6mBvkC2vEe-Fm89TGaDU3g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5Jh8YS2vEe-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5Jh8YC2vEe-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5Jh8Yi2vEe-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5Jh8Yy2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5Jh8ZC2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5Jh8ZS2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5JijcC2vEe-Fm89TGaDU3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5Jh8Zi2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_5Jijci2vEe-Fm89TGaDU3g">
            <targetForm xmi:type="expression:Expression" xmi:id="_8yPvgC2vEe-Fm89TGaDU3g" name="newForm" content="160e0105-7bb6-42fd-8d63-e8b43c83bd1b" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_5JijcS2vEe-Fm89TGaDU3g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_5JijdC2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_f69wQC2xEe-Fm89TGaDU3g" name="Recolha de requisitos" outgoing="_L5jA8B25Ee-gZr0NkXqK5g" incoming="_flYvkC22Ee-Fm89TGaDU3g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_38IQQR24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_38IQQB24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_38IQQh24Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_38IQQx24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_38IQRB24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_38IQRR24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_38IQRx24Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_38IQRh24Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_f6-XWS2xEe-Fm89TGaDU3g">
            <targetForm xmi:type="expression:Expression" xmi:id="_9Py_cC21Ee-Fm89TGaDU3g" name="newForm1" content="0e3dcedb-4c11-4675-bcf3-61bfbc40f97d" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_f6-XWC2xEe-Fm89TGaDU3g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_f6-XWy2xEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_b9mwkC22Ee-Fm89TGaDU3g" name="Step2" outgoing="_flYvkC22Ee-Fm89TGaDU3g" incoming="_fNbikC22Ee-Fm89TGaDU3g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_b9mwki22Ee-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_b9mwkS22Ee-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_b9mwky22Ee-Fm89TGaDU3g" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_-MxnACmBEe-Q4N-lG7hnAQ" name="Solicitar requisitos" definitionId="email" event="ON_ENTER" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-MxnASmBEe-Q4N-lG7hnAQ" definitionId="email" version="1.2.0" modelVersion="8">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnAimBEe-Q4N-lG7hnAQ" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnAymBEe-Q4N-lG7hnAQ" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnBCmBEe-Q4N-lG7hnAQ" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnBSmBEe-Q4N-lG7hnAQ" name="2525" content="2525" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnBimBEe-Q4N-lG7hnAQ" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnBymBEe-Q4N-lG7hnAQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnCCmBEe-Q4N-lG7hnAQ" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnCSmBEe-Q4N-lG7hnAQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnCimBEe-Q4N-lG7hnAQ" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnCymBEe-Q4N-lG7hnAQ" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnDCmBEe-Q4N-lG7hnAQ" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnDSmBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnDimBEe-Q4N-lG7hnAQ" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnDymBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnECmBEe-Q4N-lG7hnAQ" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnESmBEe-Q4N-lG7hnAQ" name="walter.bades@mail.com" content="walter.bades@mail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnEimBEe-Q4N-lG7hnAQ" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnEymBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnFCmBEe-Q4N-lG7hnAQ" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnFSmBEe-Q4N-lG7hnAQ" name="to()" content="'cliente1@mail.com'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnFimBEe-Q4N-lG7hnAQ" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnFymBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnGCmBEe-Q4N-lG7hnAQ" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnGSmBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnGimBEe-Q4N-lG7hnAQ" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnGymBEe-Q4N-lG7hnAQ" name="Solicitar requisitos" content="Solicitar requisitos" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnHCmBEe-Q4N-lG7hnAQ" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnHSmBEe-Q4N-lG7hnAQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnHimBEe-Q4N-lG7hnAQ" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnHymBEe-Q4N-lG7hnAQ" name="&lt;pattern-expression>" content="&lt;p>Solicito pr este meio os requisitos&lt;/p>&#xA;" type="TYPE_PATTERN" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnICmBEe-Q4N-lG7hnAQ" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_-MxnISmBEe-Q4N-lG7hnAQ"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnIimBEe-Q4N-lG7hnAQ" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnIymBEe-Q4N-lG7hnAQ" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnJCmBEe-Q4N-lG7hnAQ" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_-MxnJSmBEe-Q4N-lG7hnAQ" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-MxnJimBEe-Q4N-lG7hnAQ" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_-MxnJymBEe-Q4N-lG7hnAQ"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_b9mwlC22Ee-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_b9mwlS22Ee-Fm89TGaDU3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_b9mwli22Ee-Fm89TGaDU3g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_b9mwmC22Ee-Fm89TGaDU3g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_b9mwly22Ee-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_b9mwmi22Ee-Fm89TGaDU3g">
            <targetForm xmi:type="expression:Expression" xmi:id="_gc_F8C22Ee-Fm89TGaDU3g" name="newForm2" content="e72dedc4-b535-4f84-b934-7da4a8b64483" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_b9mwmS22Ee-Fm89TGaDU3g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_b9mwnC22Ee-Fm89TGaDU3g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_xHQpACKAEe-hF5ts4rL8SA" name="Utilizador que concebe a solução" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_xHQpASKAEe-hF5ts4rL8SA" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_xHQpAiKAEe-hF5ts4rL8SA" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_xHQpAyKAEe-hF5ts4rL8SA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VEyRcB0JEe-wwLkYj99nvQ" name="Equipa Técnica" actor="__SWrMCJ_Ee-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_ty458B25Ee-gZr0NkXqK5g" name="Apoio na conceção da solução" outgoing="_Ca_U8C2VEe-1jpJFqdf7Ng" incoming="_tGo38B25Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tGnp0R25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tGnp0B25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tGnp0h25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tGnp0x25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tGnp1B25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tGnp1R25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tGnp1x25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tGnp1h25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_ty5hCR25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6FS22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_ty5hCB25Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_ty5hCx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_dFCnIB26Ee-gZr0NkXqK5g" name="Apoio na conceção da melhor solução para o cliente" outgoing="_jBRVAB26Ee-gZr0NkXqK5g" incoming="_btmTEB26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_btlE8B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_btkd4R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_btlE8R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_btlE8h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_btlE8x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_btlE9B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_btlE9h26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_btlE9R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_dFDONh26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6Fi22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_dFDONR26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_dFDOOB26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_tnIgcB26Ee-gZr0NkXqK5g" name="Apoio na elaboração das justificações" outgoing="_yzsr8B26Ee-gZr0NkXqK5g" incoming="_st1g8B26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_st054B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_st0S0R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_st054R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_st054h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_st054x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_st055B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_st055h26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_st055R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_tnJukR26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6Fy22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_tnJukB26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_tnJukx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_0eI0gB26Ee-gZr0NkXqK5g" name="Calcular dias necessários e calendarização do projeto" outgoing="_-pDwYR26Ee-gZr0NkXqK5g" incoming="_yzsr8B26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_yzrd0h26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_yzrd0R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_yzrd0x26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_yzrd1B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_yzsE4B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_yzsE4R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_yzsE4x26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_yzsE4h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_0eJblB26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6GC22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_0eJbkx26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_0eJblh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_2Q-74CKAEe-hF5ts4rL8SA" name="Utilizador que apoia na concessão da solução" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_2Q-74SKAEe-hF5ts4rL8SA" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_2Q-74iKAEe-hF5ts4rL8SA" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_2Q-74yKAEe-hF5ts4rL8SA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_VTusYB0JEe-wwLkYj99nvQ" name="Serviços de Apoio ao Negócio (área logística)" actor="_NiFgUCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_7W0ZAB25Ee-gZr0NkXqK5g" name="Apoio na coordenação de recursos (logistica)" outgoing="_AscZ4R26Ee-gZr0NkXqK5g" incoming="_Ca_U8C2VEe-1jpJFqdf7Ng" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_5vQlUR25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_5vQlUB25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_5vQlUh25Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_5vQlUx25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_5vQlVB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_5vQlVR25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_5vQlVx25Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_5vQlVh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_7W1nKR25Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6GS22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_7W1nKB25Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_7W2OMB25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_9vfU0CKAEe-hF5ts4rL8SA" name="Utilizador que fornece recursos para a solução" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_9vfU0SKAEe-hF5ts4rL8SA" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_9vfU0iKAEe-hF5ts4rL8SA" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_9vfU0yKAEe-hF5ts4rL8SA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_Vkvj4B0JEe-wwLkYj99nvQ" name="Serviços de Apoio ao Negócio (área comercial)" actor="_VVkDsCKAEe-hF5ts4rL8SA">
        <elements xmi:type="process:Task" xmi:id="_BTrZAB26Ee-gZr0NkXqK5g" name="Apoio na coordenação de recursos (comercial)" outgoing="_IQ1YYB26Ee-gZr0NkXqK5g" incoming="_AscZ4R26Ee-gZr0NkXqK5g" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Asby0R26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Asby0B26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Asby0h26Ee-gZr0NkXqK5g" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Asby0x26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Asby1B26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Asby1R26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Asby1x26Ee-gZr0NkXqK5g" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Asby1h26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_BTsAGR26Ee-gZr0NkXqK5g">
            <targetForm xmi:type="expression:Expression" xmi:id="_77u6Gi22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_BTsAGB26Ee-gZr0NkXqK5g"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_BTsAGx26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <filters xmi:type="process:ActorFilter" xmi:id="_-18mkCKAEe-hF5ts4rL8SA" name="Utilizador que fornece recursos para a solução" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0">
          <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_-18mkSKAEe-hF5ts4rL8SA" definitionId="bonita-actorfilter-initiator" version="1.0">
            <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_-18mkiKAEe-hF5ts4rL8SA" key="autoAssign">
              <expression xmi:type="expression:Expression" xmi:id="_-18mkyKAEe-hF5ts4rL8SA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
            </parameters>
          </configuration>
        </filters>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_1pDqkCliEe-hQaEMBNGyoA" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda">
        <defaultValue xmi:type="expression:Expression" xmi:id="_1pDqkSliEe-hQaEMBNGyoA" name="OportunidadeDeVenda.findByPersistenceId" content="SELECT o&#xA;FROM OportunidadeDeVenda o&#xA;WHERE o.persistenceId= :persistenceId&#xA;" interpreter="GROOVY" type="TYPE_QUERY_BUSINESS_DATA" returnType="com.company.model.OportunidadeDeVenda">
          <referencedElements xmi:type="expression:Expression" xmi:id="_wXZwsC21Ee-Fm89TGaDU3g" name="persistenceId" content="persistenceId" type="QUERY_PARAM_TYPE" returnType="java.lang.Long" returnTypeFixed="true">
            <referencedElements xmi:type="expression:Expression" xmi:id="_wXZwsS21Ee-Fm89TGaDU3g" name="1" content="1" returnType="java.lang.Long" returnTypeFixed="true"/>
          </referencedElements>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_MJpihB0JEe-wwLkYj99nvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_77u6Gy22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_MJpihh0JEe-wwLkYj99nvQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_MJpihx0JEe-wwLkYj99nvQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_R5KPcB24Ee-gZr0NkXqK5g" target="_AxMDUCloEe-Q4N-lG7hnAQ" source="_QFJ7MB24Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_R5K2gB24Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_R5K2gR24Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rmkBwB24Ee-gZr0NkXqK5g" name="não" target="_rmg-cB24Ee-gZr0NkXqK5g" source="_1b4EACl_Ee-Q4N-lG7hnAQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rmko0B24Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_1JvLICl_Ee-Q4N-lG7hnAQ" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L5jA8B25Ee-gZr0NkXqK5g" target="__2TfECJ6Ee-K9NOFx4MuYQ" source="_f69wQC2xEe-Fm89TGaDU3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L5jA8R25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_L5jA8h25Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QDkxYB25Ee-gZr0NkXqK5g" target="_QDi8MB25Ee-gZr0NkXqK5g" source="__2TfECJ6Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QDkxYR25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_QDkxYh25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_aLA7cB25Ee-gZr0NkXqK5g" target="_e5Mh0B25Ee-gZr0NkXqK5g" source="_QDi8MB25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_aLA7cR25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_aLA7ch25Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tGo38B25Ee-gZr0NkXqK5g" target="_ty458B25Ee-gZr0NkXqK5g" source="_e5Mh0B25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tGo38R25Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_tGo38h25Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AscZ4R26Ee-gZr0NkXqK5g" target="_BTrZAB26Ee-gZr0NkXqK5g" source="_7W0ZAB25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AscZ4h26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_AscZ4x26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_IQ1YYB26Ee-gZr0NkXqK5g" target="_R-hlsB26Ee-gZr0NkXqK5g" source="_BTrZAB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_IQ1YYR26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_IQ1YYh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_btmTEB26Ee-gZr0NkXqK5g" target="_dFCnIB26Ee-gZr0NkXqK5g" source="_R-hlsB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_btmTER26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_btmTEh26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jBRVAB26Ee-gZr0NkXqK5g" target="_m5SIYB26Ee-gZr0NkXqK5g" source="_dFCnIB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jBRVAR26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_jBRVAh26Ee-gZr0NkXqK5g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_st1g8B26Ee-gZr0NkXqK5g" target="_tnIgcB26Ee-gZr0NkXqK5g" source="_m5SIYB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_st1g8R26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_st1g8h26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_yzsr8B26Ee-gZr0NkXqK5g" target="_0eI0gB26Ee-gZr0NkXqK5g" source="_tnIgcB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_yztTAB26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_yztTAR26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-pDwYR26Ee-gZr0NkXqK5g" target="_QGn14ClgEe-TMIDnSmPP3w" source="_0eI0gB26Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-pEXcB26Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_-pEXcR26Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BVbQAB27Ee-gZr0NkXqK5g" target="_iVrdUCJ7Ee-K9NOFx4MuYQ" source="_QGn14ClgEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BVbQAR27Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_BVbQAh27Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Kl7yEB27Ee-gZr0NkXqK5g" target="_Kl6j8B27Ee-gZr0NkXqK5g" source="_iVrdUCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Kl7yER27Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_Kl7yEh27Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_OxGK8x27Ee-gZr0NkXqK5g" target="_OxE80B27Ee-gZr0NkXqK5g" source="_Kl6j8B27Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_OxGyAB27Ee-gZr0NkXqK5g"/>
        <condition xmi:type="expression:Expression" xmi:id="_OxGyAR27Ee-gZr0NkXqK5g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_HCWPACJ7Ee-K9NOFx4MuYQ" target="_HCQvcCJ7Ee-K9NOFx4MuYQ" source="_AlWWYCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_HCXdICJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_HCXdISJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Odd8wCJ7Ee-K9NOFx4MuYQ" target="_OdcHkCJ7Ee-K9NOFx4MuYQ" source="_HCQvcCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Odd8wSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Odd8wiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XyX2oCJ7Ee-K9NOFx4MuYQ" target="_XyWBcCJ7Ee-K9NOFx4MuYQ" source="_CT_CcCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XyX2oSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_XyX2oiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_5bGgwCJ7Ee-K9NOFx4MuYQ" target="_Kl6j8B27Ee-gZr0NkXqK5g" source="_3-mtkCJ7Ee-K9NOFx4MuYQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_5bGgwSJ7Ee-K9NOFx4MuYQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_5bGgwiJ7Ee-K9NOFx4MuYQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DVNq0CleEe-TMIDnSmPP3w" target="_QFJ7MB24Ee-gZr0NkXqK5g" source="_Cy8EMCleEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DVNq0SleEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_DVNq0ileEe-TMIDnSmPP3w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_uJbXoClfEe-TMIDnSmPP3w" target="_2S3j8ClfEe-TMIDnSmPP3w" source="_OxE80B27Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_uJbXoSlfEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_uJbXoilfEe-TMIDnSmPP3w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_unGLEClfEe-TMIDnSmPP3w" target="_WeqLcClfEe-TMIDnSmPP3w" source="_2S3j8ClfEe-TMIDnSmPP3w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_unGyIClfEe-TMIDnSmPP3w"/>
        <condition xmi:type="expression:Expression" xmi:id="_unGyISlfEe-TMIDnSmPP3w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ca_U8C2VEe-1jpJFqdf7Ng" target="_7W0ZAB25Ee-gZr0NkXqK5g" source="_ty458B25Ee-gZr0NkXqK5g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ca_U8S2VEe-1jpJFqdf7Ng"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ca_U8i2VEe-1jpJFqdf7Ng" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6mBvkC2vEe-Fm89TGaDU3g" target="_5JaAkC2vEe-Fm89TGaDU3g" source="_AxMDUCloEe-Q4N-lG7hnAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6mBvkS2vEe-Fm89TGaDU3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_6mCWoC2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7e9isC2vEe-Fm89TGaDU3g" target="_1b4EACl_Ee-Q4N-lG7hnAQ" source="_5JaAkC2vEe-Fm89TGaDU3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7e9isS2vEe-Fm89TGaDU3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_7e-JwC2vEe-Fm89TGaDU3g" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fNbikC22Ee-Fm89TGaDU3g" name="sim" target="_b9mwkC22Ee-Fm89TGaDU3g" source="_1b4EACl_Ee-Q4N-lG7hnAQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fNbikS22Ee-Fm89TGaDU3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_fNbiki22Ee-Fm89TGaDU3g" name="newScript()" content="oportunidadeDeVenda.tipo_ov == &quot;venda_de_solucoes&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_5n8SgC22Ee-Fm89TGaDU3g" name="oportunidadeDeVenda" dataType="_MJpipB0JEe-wwLkYj99nvQ" className="com.company.model.OportunidadeDeVenda"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_flYvkC22Ee-Fm89TGaDU3g" target="_f69wQC2xEe-Fm89TGaDU3g" source="_b9mwkC22Ee-Fm89TGaDU3g">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_flYvkS22Ee-Fm89TGaDU3g"/>
        <condition xmi:type="expression:Expression" xmi:id="_flYvki22Ee-Fm89TGaDU3g" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="__SWrMCJ_Ee-hF5ts4rL8SA" name="Equipa Técnica"/>
      <actors xmi:type="process:Actor" xmi:id="_IfqIQCKAEe-hF5ts4rL8SA" name="Gestor da OV" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_NiFgUCKAEe-hF5ts4rL8SA" name="Serviços de Apoio ao Negócio (área logística)"/>
      <actors xmi:type="process:Actor" xmi:id="_VVkDsCKAEe-hF5ts4rL8SA" name="Serviços de Apoio ao Negócio (área comercial)"/>
      <configurations xmi:type="configuration:Configuration" xmi:id="_4BLc4CmAEe-Q4N-lG7hnAQ" name="Production" version="8" username="william.jobs">
        <actorMappings xmi:type="actormapping:ActorMappingsType" xmi:id="_4BMD8CmAEe-Q4N-lG7hnAQ">
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD8SmAEe-Q4N-lG7hnAQ" name="Equipa Técnica">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD8imAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD8ymAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD9CmAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD9SmAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD9imAEe-Q4N-lG7hnAQ" name="Gestor da OV">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD9ymAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD-CmAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD-SmAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD-imAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMD-ymAEe-Q4N-lG7hnAQ" name="Serviços de Apoio ao Negócio (área logística)">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMD_CmAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMD_SmAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMD_imAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMD_ymAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
          <actorMapping xmi:type="actormapping:ActorMapping" xmi:id="_4BMEACmAEe-Q4N-lG7hnAQ" name="Serviços de Apoio ao Negócio (área comercial)">
            <groups xmi:type="actormapping:Groups" xmi:id="_4BMEASmAEe-Q4N-lG7hnAQ"/>
            <memberships xmi:type="actormapping:Membership" xmi:id="_4BMEAimAEe-Q4N-lG7hnAQ"/>
            <roles xmi:type="actormapping:Roles" xmi:id="_4BMEAymAEe-Q4N-lG7hnAQ"/>
            <users xmi:type="actormapping:Users" xmi:id="_4BMEBCmAEe-Q4N-lG7hnAQ"/>
          </actorMapping>
        </actorMappings>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_4BLc4SmAEe-Q4N-lG7hnAQ" type="ACTOR_FILTER" definitionId="bonita-actorfilter-initiator" definitionVersion="1.0" implementationId="bonita-actorfilter-initiator-impl" implementationVersion="1.0.0"/>
        <definitionMappings xmi:type="configuration:DefinitionMapping" xmi:id="_D_Zs8CmCEe-Q4N-lG7hnAQ" type="CONNECTOR" definitionId="email" definitionVersion="1.2.0" implementationId="email-impl" implementationVersion="1.4.1"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc4imAEe-Q4N-lG7hnAQ" id="CONNECTOR">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_EC5F0CmCEe-Q4N-lG7hnAQ" id="email-impl-1.4.1">
            <fragments xmi:type="configuration:Fragment" xmi:id="_EC9XQCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="bonita-connector-email-1.4.1.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_EC_zgCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="jakarta.mail-1.6.7.jar" type="CONNECTOR"/>
            <fragments xmi:type="configuration:Fragment" xmi:id="_EDCPwCmCEe-Q4N-lG7hnAQ" key="email-impl -- 1.4.1" value="jakarta.mail-api-1.6.7.jar" type="CONNECTOR"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc4ymAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5CmAEe-Q4N-lG7hnAQ" id="ACTOR_FILTER">
          <children xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5SmAEe-Q4N-lG7hnAQ" id="bonita-actorfilter-initiator-impl-1.0.0">
            <fragments xmi:type="configuration:Fragment" xmi:id="_4BLc5imAEe-Q4N-lG7hnAQ" key="bonita-actorfilter-initiator-impl -- 1.0.0" value="bonita-actorfilter-initiator-1.0.0.jar" type="ACTOR_FILTER"/>
          </children>
        </processDependencies>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc5ymAEe-Q4N-lG7hnAQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4BLc6CmAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_MJpijB0JEe-wwLkYj99nvQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpijR0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpijh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpijx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpikB0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpikR0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpikh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpikx0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpilB0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpilR0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpilh0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpilx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpimB0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_MJpimR0JEe-wwLkYj99nvQ">
        <name xmi:type="expression:Expression" xmi:id="_MJpimh0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_MJpimx0JEe-wwLkYj99nvQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_uad6UCJ6Ee-K9NOFx4MuYQ" name="Pool1">
      <formMapping xmi:type="process:FormMapping" xmi:id="_ufT-ECJ6Ee-K9NOFx4MuYQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_787z8C22Ee-Fm89TGaDU3g" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ufT-EiJ6Ee-K9NOFx4MuYQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ufT-EyJ6Ee-K9NOFx4MuYQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <configurations xmi:type="configuration:Configuration" xmi:id="_4HA_ICmAEe-Q4N-lG7hnAQ" name="Production" version="8" username="william.jobs">
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_ISmAEe-Q4N-lG7hnAQ" id="CONNECTOR"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_IimAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_IymAEe-Q4N-lG7hnAQ" id="ACTOR_FILTER"/>
        <processDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_JCmAEe-Q4N-lG7hnAQ" id="OTHER"/>
        <applicationDependencies xmi:type="configuration:FragmentContainer" xmi:id="_4HA_JSmAEe-Q4N-lG7hnAQ" id="GROOVY_SCRIPT"/>
      </configurations>
      <contract xmi:type="process:Contract" xmi:id="_ufT-FCJ6Ee-K9NOFx4MuYQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpUCJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpUSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpUiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpUyJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpVCJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpVSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpViJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpVyJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpWCJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpWSJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpWiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpWyJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ufMpXCJ6Ee-K9NOFx4MuYQ">
        <name xmi:type="expression:Expression" xmi:id="_ufMpXSJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ufMpXiJ6Ee-K9NOFx4MuYQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_MJpinB0JEe-wwLkYj99nvQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_MJpinR0JEe-wwLkYj99nvQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_MJpinh0JEe-wwLkYj99nvQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_MJpinx0JEe-wwLkYj99nvQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_MJpioB0JEe-wwLkYj99nvQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_MJpioR0JEe-wwLkYj99nvQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_MJpioh0JEe-wwLkYj99nvQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_MJpiox0JEe-wwLkYj99nvQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_MJpipB0JEe-wwLkYj99nvQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_MJpipR0JEe-wwLkYj99nvQ" type="Process" element="_MJpicB0JEe-wwLkYj99nvQ" name="MyDiagram" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_uf07cCJ6Ee-K9NOFx4MuYQ" type="2007" element="_uad6UCJ6Ee-K9NOFx4MuYQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_uf2JkCJ6Ee-K9NOFx4MuYQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_uf2woCJ6Ee-K9NOFx4MuYQ" type="7001"/>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_uf07cSJ6Ee-K9NOFx4MuYQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_uf07ciJ6Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_uf07cyJ6Ee-K9NOFx4MuYQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_uf2woSJ6Ee-K9NOFx4MuYQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uf07dCJ6Ee-K9NOFx4MuYQ" width="1470" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_MJpiph0JEe-wwLkYj99nvQ" type="2007" element="_MJpicR0JEe-wwLkYj99nvQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_MJpipx0JEe-wwLkYj99nvQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqB0JEe-wwLkYj99nvQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_MJpiqR0JEe-wwLkYj99nvQ" type="3007" element="_MJpich0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqh0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_MJpiqx0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_QGTxwB24Ee-gZr0NkXqK5g" type="3027" element="_QFJ7MB24Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QGU_4B24Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QGTxwR24Ee-gZr0NkXqK5g" x="160" y="60" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_rmiMkB24Ee-gZr0NkXqK5g" type="3003" element="_rmg-cB24Ee-gZr0NkXqK5g" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_rmizoB24Ee-gZr0NkXqK5g" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_rmizoR24Ee-gZr0NkXqK5g" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rmiMkR24Ee-gZr0NkXqK5g" x="1166" y="21"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QDkKUB25Ee-gZr0NkXqK5g" type="3027" element="_QDi8MB25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QDkKUh25Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QDkKUR25Ee-gZr0NkXqK5g" x="702" y="61" width="181" height="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_e5Nv8B25Ee-gZr0NkXqK5g" type="3005" element="_e5Mh0B25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_e5Nv8h25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_e5Nv8R25Ee-gZr0NkXqK5g" x="860" y="179" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_R-iMyh26Ee-gZr0NkXqK5g" type="3005" element="_R-hlsB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_R-iz0B26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_R-iMyx26Ee-gZr0NkXqK5g" x="1277" y="151" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m5TWgB26Ee-gZr0NkXqK5g" type="3005" element="_m5SIYB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_m5TWgh26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m5TWgR26Ee-gZr0NkXqK5g" x="1502" y="156" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Kl7LCB27Ee-gZr0NkXqK5g" type="3027" element="_Kl6j8B27Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Kl7LCh27Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Kl7LCR27Ee-gZr0NkXqK5g" x="2054" y="139" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OxGK8B27Ee-gZr0NkXqK5g" type="3027" element="_OxE80B27Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OxGK8h27Ee-gZr0NkXqK5g" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OxGK8R27Ee-gZr0NkXqK5g" x="2270" y="148" width="150" height="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__2UtMCJ6Ee-K9NOFx4MuYQ" type="3005" element="__2TfECJ6Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="__2UtMiJ6Ee-K9NOFx4MuYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_AlYLkCJ7Ee-K9NOFx4MuYQ" type="3064" element="_AlWWYCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_AlYLkiJ7Ee-K9NOFx4MuYQ" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_AlYyoCJ7Ee-K9NOFx4MuYQ" x="-49" y="6"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AlYLkSJ7Ee-K9NOFx4MuYQ"/>
              </children>
              <children xmi:type="notation:Shape" xmi:id="_CUAQkCJ7Ee-K9NOFx4MuYQ" type="3043" element="_CT_CcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_CUAQkiJ7Ee-K9NOFx4MuYQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_CUAQkyJ7Ee-K9NOFx4MuYQ" x="56" y="-3"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CUAQkSJ7Ee-K9NOFx4MuYQ" x="90" y="62"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__2UtMSJ6Ee-K9NOFx4MuYQ" x="500" y="136" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HCR9kCJ7Ee-K9NOFx4MuYQ" type="3027" element="_HCQvcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HCR9kiJ7Ee-K9NOFx4MuYQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HCR9kSJ7Ee-K9NOFx4MuYQ" x="463" y="346" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OdcuoyJ7Ee-K9NOFx4MuYQ" type="3003" element="_OdcHkCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_OddVsCJ7Ee-K9NOFx4MuYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_OddVsSJ7Ee-K9NOFx4MuYQ" x="21" y="27"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OdcupCJ7Ee-K9NOFx4MuYQ" x="638" y="301"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XyWogyJ7Ee-K9NOFx4MuYQ" type="3003" element="_XyWBcCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_XyXPkCJ7Ee-K9NOFx4MuYQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_XyXPkSJ7Ee-K9NOFx4MuYQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XyWohCJ7Ee-K9NOFx4MuYQ" x="734" y="228"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_iVugoCJ7Ee-K9NOFx4MuYQ" type="3005" element="_iVrdUCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_iVvHsCJ7Ee-K9NOFx4MuYQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_3-n7sCJ7Ee-K9NOFx4MuYQ" type="3043" element="_3-mtkCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_3-n7siJ7Ee-K9NOFx4MuYQ" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_3-n7syJ7Ee-K9NOFx4MuYQ" x="-33" y="15"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_3-n7sSJ7Ee-K9NOFx4MuYQ"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iVugoSJ7Ee-K9NOFx4MuYQ" x="1885" y="151" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Cy95YCleEe-TMIDnSmPP3w" type="3002" element="_Cy8EMCleEe-TMIDnSmPP3w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Cy95YileEe-TMIDnSmPP3w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Cy95YyleEe-TMIDnSmPP3w" x="2" y="11"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Cy95YSleEe-TMIDnSmPP3w" x="74" y="73"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_WerZkClfEe-TMIDnSmPP3w" type="3003" element="_WeqLcClfEe-TMIDnSmPP3w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_WerZkilfEe-TMIDnSmPP3w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_WerZkylfEe-TMIDnSmPP3w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_WerZkSlfEe-TMIDnSmPP3w" x="2721" y="169"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2S4LCClfEe-TMIDnSmPP3w" type="3027" element="_2S3j8ClfEe-TMIDnSmPP3w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_2S4LCilfEe-TMIDnSmPP3w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2S4LCSlfEe-TMIDnSmPP3w" x="2474" y="150" width="144" height="72"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QGoc_ClgEe-TMIDnSmPP3w" type="3005" element="_QGn14ClgEe-TMIDnSmPP3w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QGoc_ilgEe-TMIDnSmPP3w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QGoc_SlgEe-TMIDnSmPP3w" x="1667" y="136" width="192" height="96"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_AxMqaCloEe-Q4N-lG7hnAQ" type="3027" element="_AxMDUCloEe-Q4N-lG7hnAQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_AxMqailoEe-Q4N-lG7hnAQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_AxMqaSloEe-Q4N-lG7hnAQ" x="159" y="160" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1b4rECl_Ee-Q4N-lG7hnAQ" type="3008" element="_1b4EACl_Ee-Q4N-lG7hnAQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1b4rEil_Ee-Q4N-lG7hnAQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1b4rEyl_Ee-Q4N-lG7hnAQ" x="153" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1b4rESl_Ee-Q4N-lG7hnAQ" x="368" y="60" width="41" height="41"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_5JsUcC2vEe-Fm89TGaDU3g" type="3005" element="_5JaAkC2vEe-Fm89TGaDU3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_5Js7gC2vEe-Fm89TGaDU3g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_5JsUcS2vEe-Fm89TGaDU3g" x="227" y="316"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_f6--YC2xEe-Fm89TGaDU3g" type="3005" element="_f69wQC2xEe-Fm89TGaDU3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_f6--Yi2xEe-Fm89TGaDU3g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_f6--YS2xEe-Fm89TGaDU3g" x="346" y="259" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_b9n-sC22Ee-Fm89TGaDU3g" type="3005" element="_b9mwkC22Ee-Fm89TGaDU3g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_b9n-si22Ee-Fm89TGaDU3g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_b9n-sS22Ee-Fm89TGaDU3g" x="345" y="156"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_MJpisx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_MJpitB0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_MJpitR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_MJpith0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MJpitx0JEe-wwLkYj99nvQ" x="28" y="10" width="2514" height="478"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VE1UwB0JEe-wwLkYj99nvQ" type="3007" element="_VEyRcB0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VE170B0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VE170R0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_ty6IEB25Ee-gZr0NkXqK5g" type="3005" element="_ty458B25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ty6IEh25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ty6IER25Ee-gZr0NkXqK5g" x="833" y="23" width="219" height="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dFDOOR26Ee-gZr0NkXqK5g" type="3005" element="_dFCnIB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_dFD1QB26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dFDOOh26Ee-gZr0NkXqK5g" x="1277" y="29" width="168" height="84"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tnJulB26Ee-gZr0NkXqK5g" type="3005" element="_tnIgcB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tnKVoB26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tnJulR26Ee-gZr0NkXqK5g" x="1496" y="39" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0eJblx26Ee-gZr0NkXqK5g" type="3005" element="_0eI0gB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_0eJbmR26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0eJbmB26Ee-gZr0NkXqK5g" x="1695" y="39" width="191" height="95"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VE1UwR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VE1Uwh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VE1Uwx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VE170h0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VE1UxB0JEe-wwLkYj99nvQ" x="53" y="478" width="2578" height="184"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VTv6gB0JEe-wwLkYj99nvQ" type="3007" element="_VTusYB0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VTv6hR0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VTv6hh0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_7W2OMR25Ee-gZr0NkXqK5g" type="3005" element="_7W0ZAB25Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7W2OMx25Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7W2OMh25Ee-gZr0NkXqK5g" x="837" y="46" width="212" height="106"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VTv6gR0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VTv6gh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VTv6gx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VTwhkB0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VTv6hB0JEe-wwLkYj99nvQ" x="33" y="662" width="2851" height="209"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_VkxZEB0JEe-wwLkYj99nvQ" type="3007" element="_Vkvj4B0JEe-wwLkYj99nvQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_VkyAIB0JEe-wwLkYj99nvQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_VkyAIR0JEe-wwLkYj99nvQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_BTsnIB26Ee-gZr0NkXqK5g" type="3005" element="_BTrZAB26Ee-gZr0NkXqK5g" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_BTsnIh26Ee-gZr0NkXqK5g" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_BTsnIR26Ee-gZr0NkXqK5g" x="841" y="32" width="204" height="102"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_VkxZER0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_VkxZEh0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_VkxZEx0JEe-wwLkYj99nvQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_VkyAIh0JEe-wwLkYj99nvQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_VkxZFB0JEe-wwLkYj99nvQ" x="33" y="871" width="2851" height="194"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_MJpiuB0JEe-wwLkYj99nvQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_MJpiuR0JEe-wwLkYj99nvQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_MJpiuh0JEe-wwLkYj99nvQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_MJpiux0JEe-wwLkYj99nvQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MJpivB0JEe-wwLkYj99nvQ" width="2884" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_MJpivR0JEe-wwLkYj99nvQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_R5MEoB24Ee-gZr0NkXqK5g" type="4001" element="_R5KPcB24Ee-gZr0NkXqK5g" source="_QGTxwB24Ee-gZr0NkXqK5g" target="_AxMqaCloEe-Q4N-lG7hnAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_R5MrsB24Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_R5NSwB24Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_R5MEoR24Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_R5MEoh24Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rmlP4B24Ee-gZr0NkXqK5g" type="4001" element="_rmkBwB24Ee-gZr0NkXqK5g" source="_1b4rECl_Ee-Q4N-lG7hnAQ" target="_rmiMkB24Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rml28B24Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rml28R24Ee-gZr0NkXqK5g" x="-352" y="-7"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rmlP4R24Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rmlP4h24Ee-gZr0NkXqK5g" points="[0, -21, -789, 27]$[0, -49, -789, -1]$[774, -49, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L5joAB25Ee-gZr0NkXqK5g" type="4001" element="_L5jA8B25Ee-gZr0NkXqK5g" source="_f6--YC2xEe-Fm89TGaDU3g" target="__2UtMCJ6Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L5joAx25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L5joBB25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L5joAR25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L5joAh25Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QDlYcB25Ee-gZr0NkXqK5g" type="4001" element="_QDkxYB25Ee-gZr0NkXqK5g" source="__2UtMCJ6Ee-K9NOFx4MuYQ" target="_QDkKUB25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QDlYcx25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QDlYdB25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QDlYcR25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QDlYch25Ee-gZr0NkXqK5g" points="[60, -1, -132, 90]$[96, -1, -96, 90]$[96, -93, -96, -2]$[142, -93, -50, -2]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_aLA7cx25Ee-gZr0NkXqK5g" type="4001" element="_aLA7cB25Ee-gZr0NkXqK5g" source="_QDkKUB25Ee-gZr0NkXqK5g" target="_e5Nv8B25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_aLBigB25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_aLBigR25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_aLA7dB25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_aLA7dR25Ee-gZr0NkXqK5g" points="[91, 0, -51, -110]$[134, 0, -8, -110]$[134, 73, -8, -37]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tGo38x25Ee-gZr0NkXqK5g" type="4001" element="_tGo38B25Ee-gZr0NkXqK5g" source="_e5Nv8B25Ee-gZr0NkXqK5g" target="_ty6IEB25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tGo39h25Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tGpfAB25Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tGo39B25Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tGo39R25Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AsdA8B26Ee-gZr0NkXqK5g" type="4001" element="_AscZ4R26Ee-gZr0NkXqK5g" source="_7W2OMR25Ee-gZr0NkXqK5g" target="_BTsnIB26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AsdA8x26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AsdA9B26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AsdA8R26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AsdA8h26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_IQ1YYx26Ee-gZr0NkXqK5g" type="4001" element="_IQ1YYB26Ee-gZr0NkXqK5g" source="_BTsnIB26Ee-gZr0NkXqK5g" target="_R-iMyh26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_IQ1_cB26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_IQ1_cR26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_IQ1YZB26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_IQ1YZR26Ee-gZr0NkXqK5g" points="[77, 2, -115, 695]$[105, 2, -87, 695]$[105, -694, -87, -1]$[132, -694, -60, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_btm6IB26Ee-gZr0NkXqK5g" type="4001" element="_btmTEB26Ee-gZr0NkXqK5g" source="_R-iMyh26Ee-gZr0NkXqK5g" target="_dFDOOR26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_btm6Ix26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_btm6JB26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_btm6IR26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_btm6Ih26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jBRVAx26Ee-gZr0NkXqK5g" type="4001" element="_jBRVAB26Ee-gZr0NkXqK5g" source="_dFDOOR26Ee-gZr0NkXqK5g" target="_m5TWgB26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jBR8EB26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jBR8ER26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jBRVBB26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jBRVBR26Ee-gZr0NkXqK5g" points="[84, -5, -132, 351]$[113, -5, -103, 351]$[113, -345, -103, 11]$[141, -345, -75, 11]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_st1g8x26Ee-gZr0NkXqK5g" type="4001" element="_st1g8B26Ee-gZr0NkXqK5g" source="_m5TWgB26Ee-gZr0NkXqK5g" target="_tnJulB26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_st2IAB26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_st2IAR26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_st1g9B26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_st1g9R26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_yztTAh26Ee-gZr0NkXqK5g" type="4001" element="_yzsr8B26Ee-gZr0NkXqK5g" source="_tnJulB26Ee-gZr0NkXqK5g" target="_0eJblx26Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_yztTBR26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_yztTBh26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_yztTAx26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_yztTBB26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-pEXch26Ee-gZr0NkXqK5g" type="4001" element="_-pDwYR26Ee-gZr0NkXqK5g" source="_0eJblx26Ee-gZr0NkXqK5g" target="_QGoc_ClgEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-pEXdR26Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-pEXdh26Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-pEXcx26Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-pEXdB26Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BVbQAx27Ee-gZr0NkXqK5g" type="4001" element="_BVbQAB27Ee-gZr0NkXqK5g" source="_QGoc_ClgEe-TMIDnSmPP3w" target="_iVugoCJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BVbQBh27Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BVbQBx27Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BVbQBB27Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BVbQBR27Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Kl8ZIB27Ee-gZr0NkXqK5g" type="4001" element="_Kl7yEB27Ee-gZr0NkXqK5g" source="_iVugoCJ7Ee-K9NOFx4MuYQ" target="_Kl7LCB27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Kl8ZIx27Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Kl8ZJB27Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Kl8ZIR27Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Kl8ZIh27Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_OxGyAh27Ee-gZr0NkXqK5g" type="4001" element="_OxGK8x27Ee-gZr0NkXqK5g" source="_Kl7LCB27Ee-gZr0NkXqK5g" target="_OxGK8B27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_OxGyBR27Ee-gZr0NkXqK5g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_OxGyBh27Ee-gZr0NkXqK5g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_OxGyAx27Ee-gZr0NkXqK5g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_OxGyBB27Ee-gZr0NkXqK5g" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_HCYEMCJ7Ee-K9NOFx4MuYQ" type="4001" element="_HCWPACJ7Ee-K9NOFx4MuYQ" source="_AlYLkCJ7Ee-K9NOFx4MuYQ" target="_HCR9kCJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_HCZSUCJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_HCZSUSJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_HCYrQCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_HCYrQSJ7Ee-K9NOFx4MuYQ" points="[-2, 13, -1, -92]$[-2, 70, -1, -35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Odej0CJ7Ee-K9NOFx4MuYQ" type="4001" element="_Odd8wCJ7Ee-K9NOFx4MuYQ" source="_HCR9kCJ7Ee-K9NOFx4MuYQ" target="_OdcuoyJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Odej0yJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Odej1CJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Odej0SJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Odej0iJ7Ee-K9NOFx4MuYQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XyX2oyJ7Ee-K9NOFx4MuYQ" type="4001" element="_XyX2oCJ7Ee-K9NOFx4MuYQ" source="_CUAQkCJ7Ee-K9NOFx4MuYQ" target="_XyWogyJ7Ee-K9NOFx4MuYQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XyYdsCJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XyYdsSJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XyX2pCJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XyX2pSJ7Ee-K9NOFx4MuYQ" points="[0, 13, -147, -20]$[0, 32, -147, -1]$[132, 32, -15, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_5bHu4CJ7Ee-K9NOFx4MuYQ" type="4001" element="_5bGgwCJ7Ee-K9NOFx4MuYQ" source="_3-n7sCJ7Ee-K9NOFx4MuYQ" target="_Kl7LCB27Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_5bHu4yJ7Ee-K9NOFx4MuYQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_5bHu5CJ7Ee-K9NOFx4MuYQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_5bHu4SJ7Ee-K9NOFx4MuYQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_5bHu4iJ7Ee-K9NOFx4MuYQ" points="[-13, 0, -212, 9]$[-13, 29, -212, 38]$[208, 29, 9, 38]$[208, -5, 9, 4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5bKyMCJ7Ee-K9NOFx4MuYQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_5bKyMSJ7Ee-K9NOFx4MuYQ" id="(0.44642857142857145,0.9523809523809523)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DVOR4CleEe-TMIDnSmPP3w" type="4001" element="_DVNq0CleEe-TMIDnSmPP3w" source="_Cy95YCleEe-TMIDnSmPP3w" target="_QGTxwB24Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DVOR4yleEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DVOR5CleEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DVOR4SleEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DVOR4ileEe-TMIDnSmPP3w" points="[-5, -26, -103, 7]$[85, -26, -13, 7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DVPgACleEe-TMIDnSmPP3w" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DVPgASleEe-TMIDnSmPP3w" id="(0.13,0.34)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_uJb-sClfEe-TMIDnSmPP3w" type="4001" element="_uJbXoClfEe-TMIDnSmPP3w" source="_OxGK8B27Ee-gZr0NkXqK5g" target="_2S4LCClfEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_uJb-sylfEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_uJb-tClfEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_uJb-sSlfEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_uJb-silfEe-TMIDnSmPP3w" points="[0, 2, -79, 0]$[54, -1, -25, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uJdM0ClfEe-TMIDnSmPP3w" id="(1.0,0.4266666666666667)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_uJdM0SlfEe-TMIDnSmPP3w" id="(0.1736111111111111,0.4444444444444444)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_unGyIilfEe-TMIDnSmPP3w" type="4001" element="_unGLEClfEe-TMIDnSmPP3w" source="_2S4LCClfEe-TMIDnSmPP3w" target="_WerZkClfEe-TMIDnSmPP3w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_unHZMClfEe-TMIDnSmPP3w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_unHZMSlfEe-TMIDnSmPP3w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_unGyIylfEe-TMIDnSmPP3w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_unGyJClfEe-TMIDnSmPP3w" points="[0, 9, -118, 0]$[133, 9, 15, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_unIAQClfEe-TMIDnSmPP3w" id="(1.0,0.3472222222222222)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Ca_8AC2VEe-1jpJFqdf7Ng" type="4001" element="_Ca_U8C2VEe-1jpJFqdf7Ng" source="_ty6IEB25Ee-gZr0NkXqK5g" target="_7W2OMR25Ee-gZr0NkXqK5g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ca_8Ay2VEe-1jpJFqdf7Ng" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ca_8BC2VEe-1jpJFqdf7Ng" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ca_8AS2VEe-1jpJFqdf7Ng" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ca_8Ai2VEe-1jpJFqdf7Ng" points="[0, 0, -136, -191]$[217, 196, 81, 5]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_CbC_UC2VEe-1jpJFqdf7Ng" id="(0.5283018867924528,0.9873417721518988)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6mC9sC2vEe-Fm89TGaDU3g" type="4001" element="_6mBvkC2vEe-Fm89TGaDU3g" source="_AxMqaCloEe-Q4N-lG7hnAQ" target="_5JsUcC2vEe-Fm89TGaDU3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6mDkwi2vEe-Fm89TGaDU3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6mDkwy2vEe-Fm89TGaDU3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6mDkwC2vEe-Fm89TGaDU3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6mDkwS2vEe-Fm89TGaDU3g" points="[-5, 23, 13, -75]$[-22, 95, -4, -3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6mGBAC2vEe-Fm89TGaDU3g" id="(1.0,0.5)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_6mGBAS2vEe-Fm89TGaDU3g" id="(0.28,0.08)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7e-JwS2vEe-Fm89TGaDU3g" type="4001" element="_7e9isC2vEe-Fm89TGaDU3g" source="_5JsUcC2vEe-Fm89TGaDU3g" target="_1b4rECl_Ee-Q4N-lG7hnAQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7e-w0C2vEe-Fm89TGaDU3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7e-w0S2vEe-Fm89TGaDU3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7e-Jwi2vEe-Fm89TGaDU3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7e-Jwy2vEe-Fm89TGaDU3g" points="[-20, -34, -66, 234]$[-20, -265, -66, 3]$[44, -265, -2, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7e_-8C2vEe-Fm89TGaDU3g" id="(1.0,0.68)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_7e_-8S2vEe-Fm89TGaDU3g" id="(0.11627906976744186,0.5116279069767442)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fNksgC22Ee-Fm89TGaDU3g" type="4001" element="_fNbikC22Ee-Fm89TGaDU3g" source="_1b4rECl_Ee-Q4N-lG7hnAQ" target="_b9n-sC22Ee-Fm89TGaDU3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fNksgy22Ee-Fm89TGaDU3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fNkshC22Ee-Fm89TGaDU3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fNksgS22Ee-Fm89TGaDU3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fNksgi22Ee-Fm89TGaDU3g" points="[-18, 8, -6, -60]$[-50, 64, -38, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_fNl6oC22Ee-Fm89TGaDU3g" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_flZWoC22Ee-Fm89TGaDU3g" type="4001" element="_flYvkC22Ee-Fm89TGaDU3g" source="_b9n-sC22Ee-Fm89TGaDU3g" target="_f6--YC2xEe-Fm89TGaDU3g" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_flZWoy22Ee-Fm89TGaDU3g" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_flZWpC22Ee-Fm89TGaDU3g" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_flZWoS22Ee-Fm89TGaDU3g" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_flZWoi22Ee-Fm89TGaDU3g" points="[-6, 13, 23, -62]$[-31, 53, -2, -22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_flbL0C22Ee-Fm89TGaDU3g" id="(1.0,0.66)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
